<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Errors;

class InternalServerErrorResponseThrowable extends \RuntimeException
{
    public InternalServerErrorResponse $container;

    public function __construct(string $message, int $statusCode, InternalServerErrorResponse $container)
    {
        parent::__construct($message, $statusCode);
        $this->container = $container;
    }
}