<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Operations;

use StackOne\client\Models\Components;
use StackOne\client\Utils\SpeakeasyMetadata;
class AtsCreateOfferRequest
{
    /**
     * The account identifier
     *
     * @var string $xAccountId
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=x-account-id')]
    public string $xAccountId;

    /**
     *
     * @var Components\AtsCreateOfferRequestDto $atsCreateOfferRequestDto
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\AtsCreateOfferRequestDto $atsCreateOfferRequestDto;

    /**
     * @param  string  $xAccountId
     * @param  Components\AtsCreateOfferRequestDto  $atsCreateOfferRequestDto
     */
    public function __construct(string $xAccountId, Components\AtsCreateOfferRequestDto $atsCreateOfferRequestDto)
    {
        $this->xAccountId = $xAccountId;
        $this->atsCreateOfferRequestDto = $atsCreateOfferRequestDto;
    }
}