<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Operations;

use StackOne\client\Utils\SpeakeasyMetadata;
/** AtsListJobsQueryParamFilter - ATS Jobs filters */
class AtsListJobsQueryParamFilter
{
    /**
     * Use a string with a date to only select results updated after that given date
     *
     * @var ?\DateTime $updatedAfter
     */
    #[SpeakeasyMetadata('queryParam:name=updated_after,dateTimeFormat=Y-m-d\TH:i:s.up')]
    public ?\DateTime $updatedAfter = null;

    /**
     * Use a string with a date to only select results created after that given date
     *
     * @var ?\DateTime $createdAfter
     */
    #[SpeakeasyMetadata('queryParam:name=created_after,dateTimeFormat=Y-m-d\TH:i:s.up')]
    public ?\DateTime $createdAfter = null;

    /**
     * The status of the job
     *
     * @var ?AtsListJobsQueryParamStatus $status
     * @deprecated  field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    #[SpeakeasyMetadata('queryParam:name=status')]
    public ?AtsListJobsQueryParamStatus $status = null;

    /**
     * The job_status of the job
     *
     * @var ?JobStatus $jobStatus
     */
    #[SpeakeasyMetadata('queryParam:name=job_status')]
    public ?JobStatus $jobStatus = null;

    /**
     * @param  ?\DateTime  $updatedAfter
     * @param  ?\DateTime  $createdAfter
     * @param  ?AtsListJobsQueryParamStatus  $status
     * @param  ?JobStatus  $jobStatus
     * @phpstan-pure
     */
    public function __construct(?\DateTime $updatedAfter = null, ?\DateTime $createdAfter = null, ?AtsListJobsQueryParamStatus $status = null, ?JobStatus $jobStatus = null)
    {
        $this->updatedAfter = $updatedAfter;
        $this->createdAfter = $createdAfter;
        $this->status = $status;
        $this->jobStatus = $jobStatus;
    }
}