<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Operations;

use StackOne\client\Utils\SpeakeasyMetadata;
/** AtsListApplicationsQueryParamFilter - ATS Application Filter */
class AtsListApplicationsQueryParamFilter
{
    /**
     * Use a string with a date to only select results updated after that given date
     *
     * @var ?string $updatedAfter
     */
    #[SpeakeasyMetadata('queryParam:name=updated_after')]
    public ?string $updatedAfter = null;

    /**
     * Filter to select applications by job_id
     *
     * @var ?string $jobId
     */
    #[SpeakeasyMetadata('queryParam:name=job_id')]
    public ?string $jobId = null;

    /**
     * Filter to select applications by stage and sub-stage
     *
     * @var ?string $stage
     */
    #[SpeakeasyMetadata('queryParam:name=stage')]
    public ?string $stage = null;

    /**
     * @param  ?string  $updatedAfter
     * @param  ?string  $jobId
     * @param  ?string  $stage
     */
    public function __construct(?string $updatedAfter = null, ?string $jobId = null, ?string $stage = null)
    {
        $this->updatedAfter = $updatedAfter;
        $this->jobId = $jobId;
        $this->stage = $stage;
    }
}