<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Operations;


/** Filter by the type of change that occurred to the application */
enum ChangeType: string
{
    case ApplicationStatus = 'application_status';
    case InterviewStage = 'interview_stage';
    case RejectedReasons = 'rejected_reasons';
    case UnmappedValue = 'unmapped_value';
}
