<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Operations;

use StackOne\client\Utils\SpeakeasyMetadata;
class HrisGetEmployeeTimeOffBalanceRequest
{
    /**
     * The account identifier
     *
     * @var string $xAccountId
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=x-account-id')]
    public string $xAccountId;

    /**
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     *
     * @var string $subResourceId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=subResourceId')]
    public string $subResourceId;

    /**
     * Query parameters that can be used to pass through parameters to the underlying provider request by surrounding them with 'proxy' key
     *
     * @var ?array<string, mixed> $proxy
     */
    #[SpeakeasyMetadata('queryParam:style=deepObject,explode=true,name=proxy')]
    public ?array $proxy = null;

    /**
     * The comma separated list of fields that will be returned in the response (if empty, all fields are returned)
     *
     * @var ?string $fields
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=fields')]
    public ?string $fields = null;

    /**
     * The comma separated list of fields that will be expanded in the response
     *
     * @var ?string $expand
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=expand')]
    public ?string $expand = null;

    /**
     * Indicates that the raw request result is returned
     *
     * @var ?bool $raw
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=raw')]
    public ?bool $raw = null;

    /**
     * @param  string  $xAccountId
     * @param  string  $id
     * @param  string  $subResourceId
     * @param  ?bool  $raw
     * @param  ?array<string, mixed>  $proxy
     * @param  ?string  $fields
     * @param  ?string  $expand
     * @phpstan-pure
     */
    public function __construct(string $xAccountId, string $id, string $subResourceId, ?array $proxy = null, ?string $fields = null, ?string $expand = null, ?bool $raw = false)
    {
        $this->xAccountId = $xAccountId;
        $this->id = $id;
        $this->subResourceId = $subResourceId;
        $this->proxy = $proxy;
        $this->fields = $fields;
        $this->expand = $expand;
        $this->raw = $raw;
    }
}