<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Operations;

use StackOne\client\Utils\SpeakeasyMetadata;
/** HrisListEmployeeTimeOffPoliciesQueryParamFilter - HRIS Time-Off Policies filters */
class HrisListEmployeeTimeOffPoliciesQueryParamFilter
{
    /**
     * Use a string with a date to only select results updated after that given date
     *
     * @var ?string $updatedAfter
     */
    #[SpeakeasyMetadata('queryParam:name=updated_after')]
    public ?string $updatedAfter = null;

    /**
     * Filter to select time-off policies by type
     *
     * @var ?QueryParamType $type
     */
    #[SpeakeasyMetadata('queryParam:name=type')]
    public ?QueryParamType $type = null;

    /**
     * @param  ?string  $updatedAfter
     * @param  ?QueryParamType  $type
     * @phpstan-pure
     */
    public function __construct(?string $updatedAfter = null, ?QueryParamType $type = null)
    {
        $this->updatedAfter = $updatedAfter;
        $this->type = $type;
    }
}