<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Operations;

use StackOne\client\Models\Components;
use StackOne\client\Utils\SpeakeasyMetadata;
class LmsBatchUpsertCourseRequest
{
    /**
     * The account identifier
     *
     * @var string $xAccountId
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=x-account-id')]
    public string $xAccountId;

    /**
     *
     * @var Components\LmsBatchUpsertCourseRequestDto $lmsBatchUpsertCourseRequestDto
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\LmsBatchUpsertCourseRequestDto $lmsBatchUpsertCourseRequestDto;

    /**
     * @param  string  $xAccountId
     * @param  Components\LmsBatchUpsertCourseRequestDto  $lmsBatchUpsertCourseRequestDto
     * @phpstan-pure
     */
    public function __construct(string $xAccountId, Components\LmsBatchUpsertCourseRequestDto $lmsBatchUpsertCourseRequestDto)
    {
        $this->xAccountId = $xAccountId;
        $this->lmsBatchUpsertCourseRequestDto = $lmsBatchUpsertCourseRequestDto;
    }
}