<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Operations;

use StackOne\client\Utils\SpeakeasyMetadata;
/** LmsListUserAssignmentsQueryParamFilter - LMS Assignment Filter */
class LmsListUserAssignmentsQueryParamFilter
{
    /**
     * Use a string with a date to only select results updated after that given date
     *
     * @var ?string $updatedAfter
     */
    #[SpeakeasyMetadata('queryParam:name=updated_after')]
    public ?string $updatedAfter = null;

    /**
     * Filter to select assignment by status
     *
     * @var ?QueryParamStatus $status
     */
    #[SpeakeasyMetadata('queryParam:name=status')]
    public ?QueryParamStatus $status = null;

    /**
     * Filter to select assignment by learning object type.
     *
     * @var ?LearningObjectType $learningObjectType
     */
    #[SpeakeasyMetadata('queryParam:name=learning_object_type')]
    public ?LearningObjectType $learningObjectType = null;

    /**
     * @param  ?string  $updatedAfter
     * @param  ?QueryParamStatus  $status
     * @param  ?LearningObjectType  $learningObjectType
     */
    public function __construct(?string $updatedAfter = null, ?QueryParamStatus $status = null, ?LearningObjectType $learningObjectType = null)
    {
        $this->updatedAfter = $updatedAfter;
        $this->status = $status;
        $this->learningObjectType = $learningObjectType;
    }
}