<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Operations;

use StackOne\client\Utils\SpeakeasyMetadata;
/** LmsListCoursesQueryParamFilter - LMS Courses Filter */
class LmsListCoursesQueryParamFilter
{
    /**
     * Use a string with a date to only select results updated after that given date
     *
     * @var ?string $updatedAfter
     */
    #[SpeakeasyMetadata('queryParam:name=updated_after')]
    public ?string $updatedAfter = null;

    /**
     * Filter to select courses by external_reference
     *
     * @var ?string $externalReference
     */
    #[SpeakeasyMetadata('queryParam:name=external_reference')]
    public ?string $externalReference = null;

    /**
     * @param  ?string  $updatedAfter
     * @param  ?string  $externalReference
     * @phpstan-pure
     */
    public function __construct(?string $updatedAfter = null, ?string $externalReference = null)
    {
        $this->updatedAfter = $updatedAfter;
        $this->externalReference = $externalReference;
    }
}