<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Operations;

use StackOne\client\Models\Components;
use StackOne\client\Utils\SpeakeasyMetadata;
class MarketingCreatePushTemplateRequest
{
    /**
     * The account identifier
     *
     * @var string $xAccountId
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=x-account-id')]
    public string $xAccountId;

    /**
     *
     * @var Components\MarketingCreatePushTemplateRequestDto $marketingCreatePushTemplateRequestDto
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\MarketingCreatePushTemplateRequestDto $marketingCreatePushTemplateRequestDto;

    /**
     * @param  string  $xAccountId
     * @param  Components\MarketingCreatePushTemplateRequestDto  $marketingCreatePushTemplateRequestDto
     */
    public function __construct(string $xAccountId, Components\MarketingCreatePushTemplateRequestDto $marketingCreatePushTemplateRequestDto)
    {
        $this->xAccountId = $xAccountId;
        $this->marketingCreatePushTemplateRequestDto = $marketingCreatePushTemplateRequestDto;
    }
}