<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Operations;

use StackOne\client\Models\Components;
use StackOne\client\Utils\SpeakeasyMetadata;
class MarketingCreateOmniChannelTemplateRequest
{
    /**
     * The account identifier
     *
     * @var string $xAccountId
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=x-account-id')]
    public string $xAccountId;

    /**
     *
     * @var Components\MarketingCreateTemplateRequestDto $marketingCreateTemplateRequestDto
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\MarketingCreateTemplateRequestDto $marketingCreateTemplateRequestDto;

    /**
     * @param  string  $xAccountId
     * @param  Components\MarketingCreateTemplateRequestDto  $marketingCreateTemplateRequestDto
     */
    public function __construct(string $xAccountId, Components\MarketingCreateTemplateRequestDto $marketingCreateTemplateRequestDto)
    {
        $this->xAccountId = $xAccountId;
        $this->marketingCreateTemplateRequestDto = $marketingCreateTemplateRequestDto;
    }
}