<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Operations;

use StackOne\client\Models\Components;
use StackOne\client\Utils\SpeakeasyMetadata;
class StackoneMcpPostSecurity
{
    /**
     *
     * @var ?Components\SchemeBasic $basic
     */
    #[SpeakeasyMetadata('security:scheme=true,type=http,subtype=basic')]
    public ?Components\SchemeBasic $basic = null;

    /**
     *
     * @var ?string $apiKey
     */
    #[SpeakeasyMetadata('security:scheme=true,type=apiKey,subtype=header,name=Authorization')]
    public ?string $apiKey = null;

    /**
     * @param  ?Components\SchemeBasic  $basic
     * @param  ?string  $apiKey
     * @phpstan-pure
     */
    public function __construct(?Components\SchemeBasic $basic = null, ?string $apiKey = null)
    {
        $this->basic = $basic;
        $this->apiKey = $apiKey;
    }
}