<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** AccountType - Type of the account */
class AccountType
{
    /**
     * Type of account
     *
     * @var ?JournalLineValue $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\JournalLineValue|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?JournalLineValue $value = null;

    /**
     *
     * @var string|float|bool|JournalLineSourceValue4|array<mixed>|null $sourceValue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_value')]
    #[\Speakeasy\Serializer\Annotation\Type('string|float|bool|\StackOne\client\Models\Components\JournalLineSourceValue4|array<mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public string|float|bool|JournalLineSourceValue4|array|null $sourceValue = null;

    /**
     * @param  ?JournalLineValue  $value
     * @param  string|float|bool|JournalLineSourceValue4|array<mixed>|null  $sourceValue
     * @phpstan-pure
     */
    public function __construct(?JournalLineValue $value = null, string|float|bool|JournalLineSourceValue4|array|null $sourceValue = null)
    {
        $this->value = $value;
        $this->sourceValue = $sourceValue;
    }
}