<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** AccountingAccountType - Type of account */
class AccountingAccountType
{
    /**
     * Type of account
     *
     * @var ?AccountingAccountValue $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\AccountingAccountValue|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AccountingAccountValue $value = null;

    /**
     *
     * @var string|float|bool|AccountingAccountSourceValue4|array<mixed>|null $sourceValue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_value')]
    #[\Speakeasy\Serializer\Annotation\Type('string|float|bool|\StackOne\client\Models\Components\AccountingAccountSourceValue4|array<mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public string|float|bool|AccountingAccountSourceValue4|array|null $sourceValue = null;

    /**
     * @param  ?AccountingAccountValue  $value
     * @param  string|float|bool|AccountingAccountSourceValue4|array<mixed>|null  $sourceValue
     * @phpstan-pure
     */
    public function __construct(?AccountingAccountValue $value = null, string|float|bool|AccountingAccountSourceValue4|array|null $sourceValue = null)
    {
        $this->value = $value;
        $this->sourceValue = $sourceValue;
    }
}