<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** AccountingCompanyResultBaseCurrency - Default currency for the company */
class AccountingCompanyResultBaseCurrency
{
    /**
     * Default currency for the company
     *
     * @var ?AccountingCompanyResultValue $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\AccountingCompanyResultValue|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AccountingCompanyResultValue $value = null;

    /**
     *
     * @var string|float|bool|AccountingCompanyResultSourceValue4|array<mixed>|null $sourceValue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_value')]
    #[\Speakeasy\Serializer\Annotation\Type('string|float|bool|\StackOne\client\Models\Components\AccountingCompanyResultSourceValue4|array<mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public string|float|bool|AccountingCompanyResultSourceValue4|array|null $sourceValue = null;

    /**
     * @param  ?AccountingCompanyResultValue  $value
     * @param  string|float|bool|AccountingCompanyResultSourceValue4|array<mixed>|null  $sourceValue
     * @phpstan-pure
     */
    public function __construct(?AccountingCompanyResultValue $value = null, string|float|bool|AccountingCompanyResultSourceValue4|array|null $sourceValue = null)
    {
        $this->value = $value;
        $this->sourceValue = $sourceValue;
    }
}