<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class ActionsMeta
{
    /**
     * The version of the actions metadata
     *
     * @var ?string $version
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('version')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $version = null;

    /**
     * The name of the provider
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * The unique key for the provider
     *
     * @var ?string $key
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('key')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $key = null;

    /**
     * The icon URL for the provider
     *
     * @var ?string $icon
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('icon')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $icon = null;

    /**
     * The description of the provider
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     * The authentication methods supported by the provider
     *
     * @var ?array<AuthenticationMetaItem> $authentication
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('authentication')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\StackOne\client\Models\Components\AuthenticationMetaItem>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $authentication = null;

    /**
     * The list of actions available for this provider
     *
     * @var ?array<ActionMetaItem> $actions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('actions')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\StackOne\client\Models\Components\ActionMetaItem>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $actions = null;

    /**
     * @param  ?string  $version
     * @param  ?string  $name
     * @param  ?string  $key
     * @param  ?string  $icon
     * @param  ?string  $description
     * @param  ?array<AuthenticationMetaItem>  $authentication
     * @param  ?array<ActionMetaItem>  $actions
     * @phpstan-pure
     */
    public function __construct(?string $version = null, ?string $name = null, ?string $key = null, ?string $icon = null, ?string $description = null, ?array $authentication = null, ?array $actions = null)
    {
        $this->version = $version;
        $this->name = $name;
        $this->key = $key;
        $this->icon = $icon;
        $this->description = $description;
        $this->authentication = $authentication;
        $this->actions = $actions;
    }
}