<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class AdditionalData
{
    /**
     * The type of the additional data
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * Provider's unique identifier
     *
     * @var ?string $remoteId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('remote_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $remoteId = null;

    /**
     * The value of the additional data
     *
     * @var ?AdditionalDataValue $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\AdditionalDataValue|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AdditionalDataValue $value = null;

    /**
     * @param  ?string  $id
     * @param  ?string  $remoteId
     * @param  ?AdditionalDataValue  $value
     */
    public function __construct(?string $id = null, ?string $remoteId = null, ?AdditionalDataValue $value = null)
    {
        $this->id = $id;
        $this->remoteId = $remoteId;
        $this->value = $value;
    }
}