<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class AdditionalData
{
    /**
     * The name of the additional data field. Speak to your Solutions Engineer to understand the id for the specific use case
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * Provider's unique identifier
     *
     * @var ?string $remoteId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('remote_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $remoteId = null;

    /**
     * The value of the additional data
     *
     * @var string|array<string>|null $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\Type('string|array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public string|array|null $value = null;

    /**
     * @param  ?string  $id
     * @param  ?string  $remoteId
     * @param  string|array<string>|null  $value
     * @phpstan-pure
     */
    public function __construct(?string $id = null, ?string $remoteId = null, string|array|null $value = null)
    {
        $this->id = $id;
        $this->remoteId = $remoteId;
        $this->value = $value;
    }
}