<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class Answer
{
    /**
     * Unique identifier
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * Provider's unique identifier
     *
     * @var ?string $remoteId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('remote_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $remoteId = null;

    /**
     * Type of the answer
     *
     * @var ?AnswerType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\AnswerType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AnswerType $type = null;

    /**
     * Values of the answer
     *
     * @var ?array<string> $values
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('values')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $values = null;

    /**
     * @param  ?string  $id
     * @param  ?string  $remoteId
     * @param  ?AnswerType  $type
     * @param  ?array<string>  $values
     * @phpstan-pure
     */
    public function __construct(?string $id = null, ?string $remoteId = null, ?AnswerType $type = null, ?array $values = null)
    {
        $this->id = $id;
        $this->remoteId = $remoteId;
        $this->type = $type;
        $this->values = $values;
    }
}