<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class ApplicationChanges
{
    /**
     * Timestamp when the change was created
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    public \DateTime $createdAt;

    /**
     * The new values for changed application properties. Only includes fields that commonly change over the application lifecycle.
     *
     * @var ApplicationChangesDataModel $newValues
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('new_values')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\ApplicationChangesDataModel')]
    public ApplicationChangesDataModel $newValues;

    /**
     * Unique identifier
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * Provider's unique identifier
     *
     * @var ?string $remoteId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('remote_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $remoteId = null;

    /**
     * Timestamp when the change became effective
     *
     * @var ?\DateTime $effectiveAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('effective_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $effectiveAt = null;

    /**
     * The actor who made the change
     *
     * @var ?Actor $actor
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('actor')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\Actor|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Actor $actor = null;

    /**
     * The type of change that occurred to the application
     *
     * @var ?ChangeType $changeType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('change_type')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\ChangeType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ChangeType $changeType = null;

    /**
     * @param  \DateTime  $createdAt
     * @param  ApplicationChangesDataModel  $newValues
     * @param  ?string  $id
     * @param  ?string  $remoteId
     * @param  ?\DateTime  $effectiveAt
     * @param  ?Actor  $actor
     * @param  ?ChangeType  $changeType
     * @phpstan-pure
     */
    public function __construct(\DateTime $createdAt, ApplicationChangesDataModel $newValues, ?string $id = null, ?string $remoteId = null, ?\DateTime $effectiveAt = null, ?Actor $actor = null, ?ChangeType $changeType = null)
    {
        $this->createdAt = $createdAt;
        $this->newValues = $newValues;
        $this->id = $id;
        $this->remoteId = $remoteId;
        $this->effectiveAt = $effectiveAt;
        $this->actor = $actor;
        $this->changeType = $changeType;
    }
}