<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** ApprovalStatus - The approval status of the shift */
class ApprovalStatus
{
    /**
     * The approval status of the shift
     *
     * @var ?HrisShiftApprovalStatusValue $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\HrisShiftApprovalStatusValue|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?HrisShiftApprovalStatusValue $value = null;

    /**
     *
     * @var string|float|bool|HrisShiftSourceValueApprovalStatus4|array<mixed>|null $sourceValue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_value')]
    #[\Speakeasy\Serializer\Annotation\Type('string|float|bool|\StackOne\client\Models\Components\HrisShiftSourceValueApprovalStatus4|array<mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public string|float|bool|HrisShiftSourceValueApprovalStatus4|array|null $sourceValue = null;

    /**
     * @param  ?HrisShiftApprovalStatusValue  $value
     * @param  string|float|bool|HrisShiftSourceValueApprovalStatus4|array<mixed>|null  $sourceValue
     * @phpstan-pure
     */
    public function __construct(?HrisShiftApprovalStatusValue $value = null, string|float|bool|HrisShiftSourceValueApprovalStatus4|array|null $sourceValue = null)
    {
        $this->value = $value;
        $this->sourceValue = $sourceValue;
    }
}