<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class Assignment
{
    /**
     * The ID associated with this assignment
     *
     * @var ?string $id
     */
    #[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * Provider's unique identifier
     *
     * @var ?string $remoteId
     */
    #[\JMS\Serializer\Annotation\SerializedName('remote_id')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $remoteId = null;

    /**
     * Custom Unified Fields configured in your StackOne project
     *
     * @var ?array<string, mixed> $unifiedCustomFields
     */
    #[\JMS\Serializer\Annotation\SerializedName('unified_custom_fields')]
    #[\JMS\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?array $unifiedCustomFields = null;

    /**
     * The course ID associated with this assignment
     *
     * @var ?string $courseId
     */
    #[\JMS\Serializer\Annotation\SerializedName('course_id')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $courseId = null;

    /**
     * Provider's unique identifier of the course related to the assignment
     *
     * @var ?string $remoteCourseId
     */
    #[\JMS\Serializer\Annotation\SerializedName('remote_course_id')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $remoteCourseId = null;

    /**
     * The learning_object_id associated with this assignment
     *
     * @var ?string $learningObjectId
     */
    #[\JMS\Serializer\Annotation\SerializedName('learning_object_id')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $learningObjectId = null;

    /**
     * Provider's unique identifier of the learning object related to the assignment
     *
     * @var ?string $remoteLearningObjectId
     */
    #[\JMS\Serializer\Annotation\SerializedName('remote_learning_object_id')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $remoteLearningObjectId = null;

    /**
     * The learning_object_external_reference associated with this assignment
     *
     * @var ?string $learningObjectExternalReference
     */
    #[\JMS\Serializer\Annotation\SerializedName('learning_object_external_reference')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $learningObjectExternalReference = null;

    /**
     * The progress associated with this assigment
     *
     * @var ?float $progress
     */
    #[\JMS\Serializer\Annotation\SerializedName('progress')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?float $progress = null;

    /**
     * The date the assignment was last updated
     *
     * @var ?string $updatedAt
     */
    #[\JMS\Serializer\Annotation\SerializedName('updated_at')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $updatedAt = null;

    /**
     * The date the assignment was created
     *
     * @var ?string $createdAt
     */
    #[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $createdAt = null;

    /**
     * The date the assignment is due to be completed
     *
     * @var ?string $dueDate
     */
    #[\JMS\Serializer\Annotation\SerializedName('due_date')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $dueDate = null;

    /**
     * The status of the assignment
     *
     * @var ?array<AssignmentStatusEnum> $status
     */
    #[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('array<\StackOne\client\Models\Components\AssignmentStatusEnum>|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?array $status = null;

    /**
     * The learning object type of the assignment
     *
     * @var ?array<LearningObjectTypeEnum> $learningObjectType
     */
    #[\JMS\Serializer\Annotation\SerializedName('learning_object_type')]
    #[\JMS\Serializer\Annotation\Type('array<\StackOne\client\Models\Components\LearningObjectTypeEnum>|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?array $learningObjectType = null;

    /**
     * @param  ?string  $id
     * @param  ?string  $remoteId
     * @param  ?array<string, mixed>  $unifiedCustomFields
     * @param  ?string  $courseId
     * @param  ?string  $remoteCourseId
     * @param  ?string  $learningObjectId
     * @param  ?string  $remoteLearningObjectId
     * @param  ?string  $learningObjectExternalReference
     * @param  ?float  $progress
     * @param  ?string  $updatedAt
     * @param  ?string  $createdAt
     * @param  ?string  $dueDate
     * @param  ?array<AssignmentStatusEnum>  $status
     * @param  ?array<LearningObjectTypeEnum>  $learningObjectType
     */
    public function __construct(?string $id = null, ?string $remoteId = null, ?array $unifiedCustomFields = null, ?string $courseId = null, ?string $remoteCourseId = null, ?string $learningObjectId = null, ?string $remoteLearningObjectId = null, ?string $learningObjectExternalReference = null, ?float $progress = null, ?string $updatedAt = null, ?string $createdAt = null, ?string $dueDate = null, ?array $status = null, ?array $learningObjectType = null)
    {
        $this->id = $id;
        $this->remoteId = $remoteId;
        $this->unifiedCustomFields = $unifiedCustomFields;
        $this->courseId = $courseId;
        $this->remoteCourseId = $remoteCourseId;
        $this->learningObjectId = $learningObjectId;
        $this->remoteLearningObjectId = $remoteLearningObjectId;
        $this->learningObjectExternalReference = $learningObjectExternalReference;
        $this->progress = $progress;
        $this->updatedAt = $updatedAt;
        $this->createdAt = $createdAt;
        $this->dueDate = $dueDate;
        $this->status = $status;
        $this->learningObjectType = $learningObjectType;
    }
}