<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** Confidential status of the job */
enum AtsCreateJobRequestDtoConfidential: string
{
    case True = 'true';
    case False = 'false';
    case UnmappedValue = 'unmapped_value';
}
