<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/**
 * AtsDocumentApiModelType - The content type of the document
 *
 * @deprecated  class: This will be removed in a future release, please migrate away from it as soon as possible.
 */
class AtsDocumentApiModelType
{
    /**
     * The category of the file
     *
     * @var ?AtsDocumentApiModelTypeValue $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\AtsDocumentApiModelTypeValue|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AtsDocumentApiModelTypeValue $value = null;

    /**
     *
     * @var string|float|bool|AtsDocumentApiModelSourceValueType4|array<mixed>|null $sourceValue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_value')]
    #[\Speakeasy\Serializer\Annotation\Type('string|float|bool|\StackOne\client\Models\Components\AtsDocumentApiModelSourceValueType4|array<mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public string|float|bool|AtsDocumentApiModelSourceValueType4|array|null $sourceValue = null;

    /**
     * @param  ?AtsDocumentApiModelTypeValue  $value
     * @param  string|float|bool|AtsDocumentApiModelSourceValueType4|array<mixed>|null  $sourceValue
     */
    public function __construct(?AtsDocumentApiModelTypeValue $value = null, string|float|bool|AtsDocumentApiModelSourceValueType4|array|null $sourceValue = null)
    {
        $this->value = $value;
        $this->sourceValue = $sourceValue;
    }
}