<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class AtsDocumentsUploadRequestDto
{
    /**
     * The filename of the file to upload
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * The file format of the file
     *
     * @var ?AtsDocumentsUploadRequestDtoFileFormat $fileFormat
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('file_format')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\AtsDocumentsUploadRequestDtoFileFormat|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AtsDocumentsUploadRequestDtoFileFormat $fileFormat = null;

    /**
     * The base64 encoded content of the file to upload
     *
     * @var ?string $content
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('content')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $content = null;

    /**
     * The categoryId of the documents
     *
     * @var ?string $categoryId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('category_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $categoryId = null;

    /**
     * The path for the file to be uploaded to
     *
     * @var ?string $path
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('path')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $path = null;

    /**
     * The confidentiality level of the file to be uploaded
     *
     * @var ?AtsDocumentsUploadRequestDtoConfidential $confidential
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('confidential')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\AtsDocumentsUploadRequestDtoConfidential|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AtsDocumentsUploadRequestDtoConfidential $confidential = null;

    /**
     * The category to be associated with the file to be uploaded. Id will take precedence over name.
     *
     * @var ?AtsDocumentsUploadRequestDtoCategory $category
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('category')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\AtsDocumentsUploadRequestDtoCategory|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AtsDocumentsUploadRequestDtoCategory $category = null;

    /**
     * @param  ?string  $name
     * @param  ?AtsDocumentsUploadRequestDtoFileFormat  $fileFormat
     * @param  ?string  $content
     * @param  ?string  $categoryId
     * @param  ?string  $path
     * @param  ?AtsDocumentsUploadRequestDtoConfidential  $confidential
     * @param  ?AtsDocumentsUploadRequestDtoCategory  $category
     * @phpstan-pure
     */
    public function __construct(?string $name = null, ?AtsDocumentsUploadRequestDtoFileFormat $fileFormat = null, ?string $content = null, ?string $categoryId = null, ?string $path = null, ?AtsDocumentsUploadRequestDtoConfidential $confidential = null, ?AtsDocumentsUploadRequestDtoCategory $category = null)
    {
        $this->name = $name;
        $this->fileFormat = $fileFormat;
        $this->content = $content;
        $this->categoryId = $categoryId;
        $this->path = $path;
        $this->confidential = $confidential;
        $this->category = $category;
    }
}