<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class AtsJob
{
    /**
     * Unique identifier
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * Provider's unique identifier
     *
     * @var ?string $remoteId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('remote_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $remoteId = null;

    /**
     * Custom Unified Fields configured in your StackOne project
     *
     * @var ?array<string, mixed> $unifiedCustomFields
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('unified_custom_fields')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $unifiedCustomFields = null;

    /**
     * Code of the job
     *
     * @var ?string $code
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('code')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $code = null;

    /**
     * Title of the job
     *
     * @var ?string $title
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('title')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $title = null;

    /**
     * Description of the job
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     * Status of the job
     *
     * @var ?string $status
     * @deprecated  field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $status = null;

    /**
     * Status of the job
     *
     * @var ?JobStatus $jobStatus
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('job_status')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\JobStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?JobStatus $jobStatus = null;

    /**
     * Department ids of the job
     *
     * @var ?array<string> $departmentIds
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('department_ids')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $departmentIds = null;

    /**
     * Provider's department ids of the job
     *
     * @var ?array<string> $remoteDepartmentIds
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('remote_department_ids')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $remoteDepartmentIds = null;

    /**
     * Location ids of the job
     *
     * @var ?array<string> $locationIds
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('location_ids')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $locationIds = null;

    /**
     * Provider's location ids of the job
     *
     * @var ?array<string> $remoteLocationIds
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('remote_location_ids')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $remoteLocationIds = null;

    /**
     * Hiring team for the job.
     *
     * @var ?array<AtsJobHiringTeam> $hiringTeam
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('hiring_team')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\StackOne\client\Models\Components\AtsJobHiringTeam>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $hiringTeam = null;

    /**
     * Interview stages for the job.
     *
     * @var ?array<InterviewStage> $interviewStages
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('interview_stages')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\StackOne\client\Models\Components\InterviewStage>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $interviewStages = null;

    /**
     * Confidential status of the job
     *
     * @var ?AtsJobConfidential $confidential
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('confidential')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\AtsJobConfidential|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AtsJobConfidential $confidential = null;

    /**
     * The job custom fields
     *
     * @var ?array<CustomFields> $customFields
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('custom_fields')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\StackOne\client\Models\Components\CustomFields>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $customFields = null;

    /**
     * Date of creation
     *
     * @var ?\DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdAt = null;

    /**
     * Date of last update
     *
     * @var ?\DateTime $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updated_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $updatedAt = null;

    /**
     * @param  ?string  $id
     * @param  ?string  $remoteId
     * @param  ?array<string, mixed>  $unifiedCustomFields
     * @param  ?string  $code
     * @param  ?string  $title
     * @param  ?string  $description
     * @param  ?string  $status
     * @param  ?JobStatus  $jobStatus
     * @param  ?array<string>  $departmentIds
     * @param  ?array<string>  $remoteDepartmentIds
     * @param  ?array<string>  $locationIds
     * @param  ?array<string>  $remoteLocationIds
     * @param  ?array<AtsJobHiringTeam>  $hiringTeam
     * @param  ?array<InterviewStage>  $interviewStages
     * @param  ?AtsJobConfidential  $confidential
     * @param  ?array<CustomFields>  $customFields
     * @param  ?\DateTime  $createdAt
     * @param  ?\DateTime  $updatedAt
     * @phpstan-pure
     */
    public function __construct(?string $id = null, ?string $remoteId = null, ?array $unifiedCustomFields = null, ?string $code = null, ?string $title = null, ?string $description = null, ?string $status = null, ?JobStatus $jobStatus = null, ?array $departmentIds = null, ?array $remoteDepartmentIds = null, ?array $locationIds = null, ?array $remoteLocationIds = null, ?array $hiringTeam = null, ?array $interviewStages = null, ?AtsJobConfidential $confidential = null, ?array $customFields = null, ?\DateTime $createdAt = null, ?\DateTime $updatedAt = null)
    {
        $this->id = $id;
        $this->remoteId = $remoteId;
        $this->unifiedCustomFields = $unifiedCustomFields;
        $this->code = $code;
        $this->title = $title;
        $this->description = $description;
        $this->status = $status;
        $this->jobStatus = $jobStatus;
        $this->departmentIds = $departmentIds;
        $this->remoteDepartmentIds = $remoteDepartmentIds;
        $this->locationIds = $locationIds;
        $this->remoteLocationIds = $remoteLocationIds;
        $this->hiringTeam = $hiringTeam;
        $this->interviewStages = $interviewStages;
        $this->confidential = $confidential;
        $this->customFields = $customFields;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
    }
}