<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class AtsUpdateApplicationRequestDto
{
    /**
     * Value to pass through to the provider
     *
     * @var ?array<string, mixed> $passthrough
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('passthrough')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $passthrough = null;

    /**
     * Unique identifier of the rejection reason
     *
     * @var ?string $rejectedReasonId
     * @deprecated  field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('rejected_reason_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $rejectedReasonId = null;

    /**
     * The application custom fields
     *
     * @var ?array<ApplicationCustomFields> $customFields
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('custom_fields')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\StackOne\client\Models\Components\ApplicationCustomFields>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $customFields = null;

    /**
     *
     * @var ?AtsUpdateApplicationRequestDtoApplicationStatus $applicationStatus
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('application_status')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\AtsUpdateApplicationRequestDtoApplicationStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AtsUpdateApplicationRequestDtoApplicationStatus $applicationStatus = null;

    /**
     *
     * @var ?AtsUpdateApplicationRequestDtoSource $source
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\AtsUpdateApplicationRequestDtoSource|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AtsUpdateApplicationRequestDtoSource $source = null;

    /**
     * Unique identifier of the interview stage
     *
     * @var ?string $interviewStageId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('interview_stage_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $interviewStageId = null;

    /**
     * @param  ?array<string, mixed>  $passthrough
     * @param  ?string  $rejectedReasonId
     * @param  ?array<ApplicationCustomFields>  $customFields
     * @param  ?AtsUpdateApplicationRequestDtoApplicationStatus  $applicationStatus
     * @param  ?AtsUpdateApplicationRequestDtoSource  $source
     * @param  ?string  $interviewStageId
     */
    public function __construct(?array $passthrough = null, ?string $rejectedReasonId = null, ?array $customFields = null, ?AtsUpdateApplicationRequestDtoApplicationStatus $applicationStatus = null, ?AtsUpdateApplicationRequestDtoSource $source = null, ?string $interviewStageId = null)
    {
        $this->passthrough = $passthrough;
        $this->rejectedReasonId = $rejectedReasonId;
        $this->customFields = $customFields;
        $this->applicationStatus = $applicationStatus;
        $this->source = $source;
        $this->interviewStageId = $interviewStageId;
    }
}