<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class AtsUpdateBackgroundCheckResultRequestDtoCandidate
{
    /**
     * Unique identifier
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * Candidate profile url
     *
     * @var ?string $profileUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('profile_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $profileUrl = null;

    /**
     * @param  ?string  $id
     * @param  ?string  $profileUrl
     * @phpstan-pure
     */
    public function __construct(?string $id = null, ?string $profileUrl = null)
    {
        $this->id = $id;
        $this->profileUrl = $profileUrl;
    }
}