<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** AtsUpdateJobRequestDtoJobStatus - Status of the job */
class AtsUpdateJobRequestDtoJobStatus
{
    /**
     * The status of the job.
     *
     * @var ?AtsUpdateJobRequestDtoValue $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\AtsUpdateJobRequestDtoValue|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AtsUpdateJobRequestDtoValue $value = null;

    /**
     * The source value of the job status.
     *
     * @var string|float|bool|AtsUpdateJobRequestDtoSourceValue4|array<mixed>|null $sourceValue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_value')]
    #[\Speakeasy\Serializer\Annotation\Type('string|float|bool|\StackOne\client\Models\Components\AtsUpdateJobRequestDtoSourceValue4|array<mixed>')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public string|float|bool|AtsUpdateJobRequestDtoSourceValue4|array|null $sourceValue = null;

    /**
     * @param  ?AtsUpdateJobRequestDtoValue  $value
     * @param  string|float|bool|AtsUpdateJobRequestDtoSourceValue4|array<mixed>|null  $sourceValue
     */
    public function __construct(?AtsUpdateJobRequestDtoValue $value = null, string|float|bool|AtsUpdateJobRequestDtoSourceValue4|array|null $sourceValue = null)
    {
        $this->value = $value;
        $this->sourceValue = $sourceValue;
    }
}