<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class BackgroundCheckOrder
{
    /**
     * Unique identifier
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * Provider's unique identifier
     *
     * @var ?string $remoteId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('remote_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $remoteId = null;

    /**
     *
     * @var ?BackgroundCheckOrderApplication $application
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('application')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\BackgroundCheckOrderApplication|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?BackgroundCheckOrderApplication $application = null;

    /**
     *
     * @var ?BackgroundCheckOrderJob $job
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('job')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\BackgroundCheckOrderJob|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?BackgroundCheckOrderJob $job = null;

    /**
     *
     * @var ?BackgroundCheckOrderCandidate $candidate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('candidate')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\BackgroundCheckOrderCandidate|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?BackgroundCheckOrderCandidate $candidate = null;

    /**
     *
     * @var ?BackgroundCheckOrderRequester $requester
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('requester')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\BackgroundCheckOrderRequester|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?BackgroundCheckOrderRequester $requester = null;

    /**
     * Results update url
     *
     * @var ?string $resultsUpdateUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('results_update_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $resultsUpdateUrl = null;

    /**
     *
     * @var ?BackgroundCheckOrderPackage $package
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('package')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\BackgroundCheckOrderPackage|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?BackgroundCheckOrderPackage $package = null;

    /**
     * @param  ?string  $id
     * @param  ?string  $remoteId
     * @param  ?BackgroundCheckOrderApplication  $application
     * @param  ?BackgroundCheckOrderJob  $job
     * @param  ?BackgroundCheckOrderCandidate  $candidate
     * @param  ?BackgroundCheckOrderRequester  $requester
     * @param  ?string  $resultsUpdateUrl
     * @param  ?BackgroundCheckOrderPackage  $package
     * @phpstan-pure
     */
    public function __construct(?string $id = null, ?string $remoteId = null, ?BackgroundCheckOrderApplication $application = null, ?BackgroundCheckOrderJob $job = null, ?BackgroundCheckOrderCandidate $candidate = null, ?BackgroundCheckOrderRequester $requester = null, ?string $resultsUpdateUrl = null, ?BackgroundCheckOrderPackage $package = null)
    {
        $this->id = $id;
        $this->remoteId = $remoteId;
        $this->application = $application;
        $this->job = $job;
        $this->candidate = $candidate;
        $this->requester = $requester;
        $this->resultsUpdateUrl = $resultsUpdateUrl;
        $this->package = $package;
    }
}