<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** The schedule type of the campaign. */
enum CampaignValue: string
{
    case Immediate = 'immediate';
    case Scheduled = 'scheduled';
    case Recurring = 'recurring';
    case Custom = 'custom';
    case Triggered = 'triggered';
}
