<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class ClearingCode
{
    /**
     * The type of clearing code
     *
     * @var ?ClearingCodeType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\ClearingCodeType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ClearingCodeType $type = null;

    /**
     * The clearing code value
     *
     * @var ?string $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $value = null;

    /**
     * @param  ?ClearingCodeType  $type
     * @param  ?string  $value
     * @phpstan-pure
     */
    public function __construct(?ClearingCodeType $type = null, ?string $value = null)
    {
        $this->type = $type;
        $this->value = $value;
    }
}