<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** Confidential - The confidentiality level of the file to be uploaded */
class Confidential
{
    /**
     * Whether the file is confidential or not
     *
     * @var ?HrisDocumentsUploadRequestDtoConfidentialValue $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\HrisDocumentsUploadRequestDtoConfidentialValue|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?HrisDocumentsUploadRequestDtoConfidentialValue $value = null;

    /**
     *
     * @var string|float|bool|HrisDocumentsUploadRequestDtoSourceValueConfidential4|array<mixed>|null $sourceValue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_value')]
    #[\Speakeasy\Serializer\Annotation\Type('string|float|bool|\StackOne\client\Models\Components\HrisDocumentsUploadRequestDtoSourceValueConfidential4|array<mixed>')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public string|float|bool|HrisDocumentsUploadRequestDtoSourceValueConfidential4|array|null $sourceValue = null;

    /**
     * @param  ?HrisDocumentsUploadRequestDtoConfidentialValue  $value
     * @param  string|float|bool|HrisDocumentsUploadRequestDtoSourceValueConfidential4|array<mixed>|null  $sourceValue
     */
    public function __construct(?HrisDocumentsUploadRequestDtoConfidentialValue $value = null, string|float|bool|HrisDocumentsUploadRequestDtoSourceValueConfidential4|array|null $sourceValue = null)
    {
        $this->value = $value;
        $this->sourceValue = $sourceValue;
    }
}