<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** ConnectSessionTokenAuthLinkMetadata - Arbitrary set of key and values defined during the session token creation. This can be used to tag an account (eg. based on their pricing plan) */
class ConnectSessionTokenAuthLinkMetadata
{

    public function __construct()
    {
    }
}