<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class ConnectSessionCreate
{
    /**
     * The origin owner identifier
     *
     * @var string $originOwnerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('origin_owner_id')]
    public string $originOwnerId;

    /**
     * The origin owner name
     *
     * @var string $originOwnerName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('origin_owner_name')]
    public string $originOwnerName;

    /**
     * The categories of the provider to connect to
     *
     * @var ?array<Categories> $categories
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('categories')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\StackOne\client\Models\Components\Categories>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $categories = null;

    /**
     * The provider to connect to
     *
     * @var ?string $provider
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('provider')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $provider = null;

    /**
     * The provider version to connect to
     *
     * @var ?string $providerVersion
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('provider_version')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $providerVersion = null;

    /**
     * The origin username
     *
     * @var ?string $originUsername
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('origin_username')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $originUsername = null;

    /**
     * The unique identifier for the account associated with this connect session. When this field is present, the hub will launch in edit mode using the retrieved token.
     *
     * @var ?string $accountId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('account_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $accountId = null;

    /**
     * The metadata for the connection
     *
     * @var ?Metadata $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\Metadata|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Metadata $metadata = null;

    /**
     * The label to be applied to the account associated with this connect session.
     *
     * @var ?string $label
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('label')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $label = null;

    /**
     * How long the session should be valid for in seconds
     *
     * @var ?float $expiresIn
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expires_in')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $expiresIn = null;

    /**
     * If set, this connect session will allow creation of multiple accounts with the same origin owner id and provider. Has no effect if account_id is set.
     *
     * @var ?bool $multiple
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('multiple')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $multiple = null;

    /**
     * The connect session account type
     *
     * @var ?Type $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\Type|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Type $type = null;

    /**
     * @param  string  $originOwnerId
     * @param  string  $originOwnerName
     * @param  ?array<Categories>  $categories
     * @param  ?string  $provider
     * @param  ?string  $providerVersion
     * @param  ?string  $originUsername
     * @param  ?string  $accountId
     * @param  ?float  $expiresIn
     * @param  ?Metadata  $metadata
     * @param  ?bool  $multiple
     * @param  ?string  $label
     * @param  ?Type  $type
     * @phpstan-pure
     */
    public function __construct(string $originOwnerId, string $originOwnerName, ?array $categories = null, ?string $provider = null, ?string $providerVersion = null, ?string $originUsername = null, ?string $accountId = null, ?Metadata $metadata = null, ?string $label = null, ?float $expiresIn = 1800, ?bool $multiple = false, ?Type $type = Type::Production)
    {
        $this->originOwnerId = $originOwnerId;
        $this->originOwnerName = $originOwnerName;
        $this->categories = $categories;
        $this->provider = $provider;
        $this->providerVersion = $providerVersion;
        $this->originUsername = $originUsername;
        $this->accountId = $accountId;
        $this->metadata = $metadata;
        $this->label = $label;
        $this->expiresIn = $expiresIn;
        $this->multiple = $multiple;
        $this->type = $type;
    }
}