<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class ContentType
{
    /**
     * The content type of the attachment.
     *
     * @var ?ApplicationAttachmentValue $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\ApplicationAttachmentValue|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ApplicationAttachmentValue $value = null;

    /**
     * The source value of the content type.
     *
     * @var string|float|bool|ApplicationAttachmentSourceValue4|array<mixed>|null $sourceValue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_value')]
    #[\Speakeasy\Serializer\Annotation\Type('string|float|bool|\StackOne\client\Models\Components\ApplicationAttachmentSourceValue4|array<mixed>')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public string|float|bool|ApplicationAttachmentSourceValue4|array|null $sourceValue = null;

    /**
     * @param  ?ApplicationAttachmentValue  $value
     * @param  string|float|bool|ApplicationAttachmentSourceValue4|array<mixed>|null  $sourceValue
     */
    public function __construct(?ApplicationAttachmentValue $value = null, string|float|bool|ApplicationAttachmentSourceValue4|array|null $sourceValue = null)
    {
        $this->value = $value;
        $this->sourceValue = $sourceValue;
    }
}