<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** ContractType - The employment work schedule type */
class ContractType
{
    /**
     * Unique identifier
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * Provider's unique identifier
     *
     * @var ?string $remoteId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('remote_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $remoteId = null;

    /**
     * The label of the employment type
     *
     * @var ?string $label
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('label')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $label = null;

    /**
     * The employment work schedule type (e.g., full-time, part-time)
     *
     * @var ?EmploymentContractTypeContractType $contractType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('contract_type')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\EmploymentContractTypeContractType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?EmploymentContractTypeContractType $contractType = null;

    /**
     * @param  ?string  $id
     * @param  ?string  $remoteId
     * @param  ?string  $label
     * @param  ?EmploymentContractTypeContractType  $contractType
     * @phpstan-pure
     */
    public function __construct(?string $id = null, ?string $remoteId = null, ?string $label = null, ?EmploymentContractTypeContractType $contractType = null)
    {
        $this->id = $id;
        $this->remoteId = $remoteId;
        $this->label = $label;
        $this->contractType = $contractType;
    }
}