<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class CostCenters
{
    /**
     *
     * @var ?string $name
     */
    #[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     *
     * @var ?float $distributionPercentage
     */
    #[\JMS\Serializer\Annotation\SerializedName('distribution_percentage')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?float $distributionPercentage = null;

    /**
     * @param  ?string  $name
     * @param  ?float  $distributionPercentage
     */
    public function __construct(?string $name = null, ?float $distributionPercentage = null)
    {
        $this->name = $name;
        $this->distributionPercentage = $distributionPercentage;
    }
}