<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** CountryCode - The country code where the bank is located */
class CountryCode
{
    /**
     * The ISO3166-1 Alpha2 Code of the Country
     *
     * @var ?HRISBankDetailsValue $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\HRISBankDetailsValue|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?HRISBankDetailsValue $value = null;

    /**
     *
     * @var string|float|bool|HRISBankDetailsSourceValue4|array<mixed>|null $sourceValue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_value')]
    #[\Speakeasy\Serializer\Annotation\Type('string|float|bool|\StackOne\client\Models\Components\HRISBankDetailsSourceValue4|array<mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public string|float|bool|HRISBankDetailsSourceValue4|array|null $sourceValue = null;

    /**
     * @param  ?HRISBankDetailsValue  $value
     * @param  string|float|bool|HRISBankDetailsSourceValue4|array<mixed>|null  $sourceValue
     * @phpstan-pure
     */
    public function __construct(?HRISBankDetailsValue $value = null, string|float|bool|HRISBankDetailsSourceValue4|array|null $sourceValue = null)
    {
        $this->value = $value;
        $this->sourceValue = $sourceValue;
    }
}