<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class CreateResult
{
    /**
     *
     * @var float $statusCode
     */
    #[\JMS\Serializer\Annotation\SerializedName('statusCode')]
    public float $statusCode;

    /**
     *
     * @var string $message
     */
    #[\JMS\Serializer\Annotation\SerializedName('message')]
    public string $message;

    /**
     *
     * @var \DateTime $timestamp
     */
    #[\JMS\Serializer\Annotation\SerializedName('timestamp')]
    public \DateTime $timestamp;

    /**
     *
     * @var CreateResultDataApiModel $data
     */
    #[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('\StackOne\client\Models\Components\CreateResultDataApiModel')]
    public CreateResultDataApiModel $data;

    /**
     * @param  float  $statusCode
     * @param  string  $message
     * @param  \DateTime  $timestamp
     * @param  CreateResultDataApiModel  $data
     */
    public function __construct(float $statusCode, string $message, \DateTime $timestamp, CreateResultDataApiModel $data)
    {
        $this->statusCode = $statusCode;
        $this->message = $message;
        $this->timestamp = $timestamp;
        $this->data = $data;
    }
}