<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** The unified category level. For write operations: provide one of the listed enum values, or omit/set to "unmapped_value" to use source_value instead. */
enum CreateCategoriesApiModelLevelValue: string
{
    case Primary = 'primary';
    case Secondary = 'secondary';
    case Tertiary = 'tertiary';
    case UnmappedValue = 'unmapped_value';
}
