<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class CreateEmploymentApiModel
{
    /**
     * Custom Unified Fields configured in your StackOne project
     *
     * @var ?array<string, mixed> $unifiedCustomFields
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('unified_custom_fields')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $unifiedCustomFields = null;

    /**
     * The job title of the employee
     *
     * @var ?string $jobTitle
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('job_title')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $jobTitle = null;

    /**
     * The pay rate for the employee
     *
     * @var ?string $payRate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pay_rate')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $payRate = null;

    /**
     * The pay period
     *
     * @var ?CreateEmploymentApiModelPayPeriod $payPeriod
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pay_period')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\CreateEmploymentApiModelPayPeriod|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CreateEmploymentApiModelPayPeriod $payPeriod = null;

    /**
     * The pay frequency
     *
     * @var ?CreateEmploymentApiModelPayFrequency $payFrequency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pay_frequency')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\CreateEmploymentApiModelPayFrequency|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CreateEmploymentApiModelPayFrequency $payFrequency = null;

    /**
     * The currency used for pay
     *
     * @var ?string $payCurrency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pay_currency')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $payCurrency = null;

    /**
     * The effective date of the employment contract
     *
     * @var ?\DateTime $effectiveDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('effective_date')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $effectiveDate = null;

    /**
     * The end date of employment
     *
     * @var ?\DateTime $endDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('end_date')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $endDate = null;

    /**
     * Represents the employee’s position within the organizational hierarchy.
     *
     * @var ?CreateEmploymentApiModelGrade $grade
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('grade')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\CreateEmploymentApiModelGrade|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CreateEmploymentApiModelGrade $grade = null;

    /**
     * The type of employment (e.g., contractor, permanent)
     *
     * @var ?CreateEmploymentApiModelEmploymentType $employmentType
     * @deprecated  field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('employment_type')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\CreateEmploymentApiModelEmploymentType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CreateEmploymentApiModelEmploymentType $employmentType = null;

    /**
     * The employment work schedule type (e.g., full-time, part-time)
     *
     * @var ?CreateEmploymentApiModelEmploymentContractType $employmentContractType
     * @deprecated  field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('employment_contract_type')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\CreateEmploymentApiModelEmploymentContractType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CreateEmploymentApiModelEmploymentContractType $employmentContractType = null;

    /**
     *
     * @var ?CreateEmploymentApiModelWorkTime $workTime
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('work_time')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\CreateEmploymentApiModelWorkTime|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CreateEmploymentApiModelWorkTime $workTime = null;

    /**
     * The payroll code of the employee
     *
     * @var ?string $payrollCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('payroll_code')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $payrollCode = null;

    /**
     * The employee job id
     *
     * @var ?string $jobId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('job_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $jobId = null;

    /**
     * @param  ?array<string, mixed>  $unifiedCustomFields
     * @param  ?string  $jobTitle
     * @param  ?string  $payRate
     * @param  ?CreateEmploymentApiModelPayPeriod  $payPeriod
     * @param  ?CreateEmploymentApiModelPayFrequency  $payFrequency
     * @param  ?string  $payCurrency
     * @param  ?\DateTime  $effectiveDate
     * @param  ?\DateTime  $endDate
     * @param  ?CreateEmploymentApiModelGrade  $grade
     * @param  ?CreateEmploymentApiModelEmploymentType  $employmentType
     * @param  ?CreateEmploymentApiModelEmploymentContractType  $employmentContractType
     * @param  ?CreateEmploymentApiModelWorkTime  $workTime
     * @param  ?string  $payrollCode
     * @param  ?string  $jobId
     * @phpstan-pure
     */
    public function __construct(?array $unifiedCustomFields = null, ?string $jobTitle = null, ?string $payRate = null, ?CreateEmploymentApiModelPayPeriod $payPeriod = null, ?CreateEmploymentApiModelPayFrequency $payFrequency = null, ?string $payCurrency = null, ?\DateTime $effectiveDate = null, ?\DateTime $endDate = null, ?CreateEmploymentApiModelGrade $grade = null, ?CreateEmploymentApiModelEmploymentType $employmentType = null, ?CreateEmploymentApiModelEmploymentContractType $employmentContractType = null, ?CreateEmploymentApiModelWorkTime $workTime = null, ?string $payrollCode = null, ?string $jobId = null)
    {
        $this->unifiedCustomFields = $unifiedCustomFields;
        $this->jobTitle = $jobTitle;
        $this->payRate = $payRate;
        $this->payPeriod = $payPeriod;
        $this->payFrequency = $payFrequency;
        $this->payCurrency = $payCurrency;
        $this->effectiveDate = $effectiveDate;
        $this->endDate = $endDate;
        $this->grade = $grade;
        $this->employmentType = $employmentType;
        $this->employmentContractType = $employmentContractType;
        $this->workTime = $workTime;
        $this->payrollCode = $payrollCode;
        $this->jobId = $jobId;
    }
}