<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** EmailMessagesValue - The unified message type. */
class EmailMessagesValue
{

    public function __construct()
    {
    }
}