<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** The type of the national identity number */
enum EmployeeNationalIdentityNumberValue: string
{
    case Ssn = 'ssn';
    case Nin = 'nin';
    case Sin = 'sin';
    case Other = 'other';
    case Unknown = 'unknown';
}
