<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/**
 * EmploymentContractType - The employment work schedule type (e.g., full-time, part-time)
 *
 * @deprecated  class: This will be removed in a future release, please migrate away from it as soon as possible.
 */
class EmploymentContractType
{
    /**
     *
     * @var ?EmployeeEmploymentContractTypeValue $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\EmployeeEmploymentContractTypeValue|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?EmployeeEmploymentContractTypeValue $value = null;

    /**
     *
     * @var string|float|bool|EmployeeSourceValueEmploymentContractType4|array<mixed>|null $sourceValue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_value')]
    #[\Speakeasy\Serializer\Annotation\Type('string|float|bool|\StackOne\client\Models\Components\EmployeeSourceValueEmploymentContractType4|array<mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public string|float|bool|EmployeeSourceValueEmploymentContractType4|array|null $sourceValue = null;

    /**
     * @param  ?EmployeeEmploymentContractTypeValue  $value
     * @param  string|float|bool|EmployeeSourceValueEmploymentContractType4|array<mixed>|null  $sourceValue
     */
    public function __construct(?EmployeeEmploymentContractTypeValue $value = null, string|float|bool|EmployeeSourceValueEmploymentContractType4|array|null $sourceValue = null)
    {
        $this->value = $value;
        $this->sourceValue = $sourceValue;
    }
}