<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** EmployeeLocationType - The location type */
class EmployeeLocationType
{
    /**
     * The type of the location.
     *
     * @var ?EmployeeWorkLocationLocationTypeValue $value
     */
    #[\JMS\Serializer\Annotation\SerializedName('value')]
    #[\JMS\Serializer\Annotation\Type('\StackOne\client\Models\Components\EmployeeWorkLocationLocationTypeValue|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?EmployeeWorkLocationLocationTypeValue $value = null;

    /**
     * The source value of the location type.
     *
     * @var string|float|bool|EmployeeSourceValueWorkLocationLocationType4|array<mixed>|null $sourceValue
     */
    #[\JMS\Serializer\Annotation\SerializedName('source_value')]
    #[\JMS\Serializer\Annotation\Type('string|float|bool|\StackOne\client\Models\Components\EmployeeSourceValueWorkLocationLocationType4|array<mixed>')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public string|float|bool|EmployeeSourceValueWorkLocationLocationType4|array|null $sourceValue = null;

    /**
     * @param  ?EmployeeWorkLocationLocationTypeValue  $value
     * @param  string|float|bool|EmployeeSourceValueWorkLocationLocationType4|array<mixed>|null  $sourceValue
     */
    public function __construct(?EmployeeWorkLocationLocationTypeValue $value = null, string|float|bool|EmployeeSourceValueWorkLocationLocationType4|array|null $sourceValue = null)
    {
        $this->value = $value;
        $this->sourceValue = $sourceValue;
    }
}