<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** Ethnicity - The employee ethnicity */
class Ethnicity
{
    /**
     *
     * @var ?EmployeeEthnicityValue $value
     */
    #[\JMS\Serializer\Annotation\SerializedName('value')]
    #[\JMS\Serializer\Annotation\Type('\StackOne\client\Models\Components\EmployeeEthnicityValue|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?EmployeeEthnicityValue $value = null;

    /**
     *
     * @var string|float|bool|EmployeeSourceValueEthnicity4|array<mixed>|null $sourceValue
     */
    #[\JMS\Serializer\Annotation\SerializedName('source_value')]
    #[\JMS\Serializer\Annotation\Type('string|float|bool|\StackOne\client\Models\Components\EmployeeSourceValueEthnicity4|array<mixed>')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public string|float|bool|EmployeeSourceValueEthnicity4|array|null $sourceValue = null;

    /**
     * @param  ?EmployeeEthnicityValue  $value
     * @param  string|float|bool|EmployeeSourceValueEthnicity4|array<mixed>|null  $sourceValue
     */
    public function __construct(?EmployeeEthnicityValue $value = null, string|float|bool|EmployeeSourceValueEthnicity4|array|null $sourceValue = null)
    {
        $this->value = $value;
        $this->sourceValue = $sourceValue;
    }
}