<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class HrisUpdateEmploymentRequestDtoWorkTime
{
    /**
     * The work time duration in ISO 8601 duration format
     *
     * @var ?string $duration
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('duration')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $duration = null;

    /**
     * The period of the work time
     *
     * @var ?HrisUpdateEmploymentRequestDtoPeriod $period
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('period')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\HrisUpdateEmploymentRequestDtoPeriod|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?HrisUpdateEmploymentRequestDtoPeriod $period = null;

    /**
     * @param  ?string  $duration
     * @param  ?HrisUpdateEmploymentRequestDtoPeriod  $period
     * @phpstan-pure
     */
    public function __construct(?string $duration = null, ?HrisUpdateEmploymentRequestDtoPeriod $period = null)
    {
        $this->duration = $duration;
        $this->period = $period;
    }
}