<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** HrisCreateEmployeeRequestDtoNationalIdentityNumber - The national identity number */
class HrisCreateEmployeeRequestDtoNationalIdentityNumber
{
    /**
     *
     * @var ?string $value
     */
    #[\JMS\Serializer\Annotation\SerializedName('value')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $value = null;

    /**
     *
     * @var ?HrisCreateEmployeeRequestDtoType $type
     */
    #[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('\StackOne\client\Models\Components\HrisCreateEmployeeRequestDtoType|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?HrisCreateEmployeeRequestDtoType $type = null;

    /**
     * @param  ?string  $value
     * @param  ?HrisCreateEmployeeRequestDtoType  $type
     */
    public function __construct(?string $value = null, ?HrisCreateEmployeeRequestDtoType $type = null)
    {
        $this->value = $value;
        $this->type = $type;
    }
}