<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** HrisDocumentsUploadRequestDtoCategory - The category to be associated with the file to be uploaded. Id will take precedence over name. */
class HrisDocumentsUploadRequestDtoCategory
{
    /**
     * The category name to associate with the file
     *
     * @var ?HrisDocumentsUploadRequestDtoCategoryValue $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\HrisDocumentsUploadRequestDtoCategoryValue|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?HrisDocumentsUploadRequestDtoCategoryValue $value = null;

    /**
     * The provider specific category for associating uploaded files, if provided, the value will be ignored.
     *
     * @var ?string $sourceValue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_value')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $sourceValue = null;

    /**
     * @param  ?HrisDocumentsUploadRequestDtoCategoryValue  $value
     * @param  ?string  $sourceValue
     * @phpstan-pure
     */
    public function __construct(?HrisDocumentsUploadRequestDtoCategoryValue $value = null, ?string $sourceValue = null)
    {
        $this->value = $value;
        $this->sourceValue = $sourceValue;
    }
}