<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** HrisUpdateEmployeeRequestDtoState - The ISO3166-2 sub division where the location is situated */
class HrisUpdateEmployeeRequestDtoState
{
    /**
     *
     * @var ?HrisUpdateEmployeeRequestDtoHomeLocationStateValue $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\HrisUpdateEmployeeRequestDtoHomeLocationStateValue|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?HrisUpdateEmployeeRequestDtoHomeLocationStateValue $value = null;

    /**
     *
     * @var string|float|bool|HrisUpdateEmployeeRequestDtoSourceValueHomeLocationState4|array<mixed>|null $sourceValue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_value')]
    #[\Speakeasy\Serializer\Annotation\Type('string|float|bool|\StackOne\client\Models\Components\HrisUpdateEmployeeRequestDtoSourceValueHomeLocationState4|array<mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public string|float|bool|HrisUpdateEmployeeRequestDtoSourceValueHomeLocationState4|array|null $sourceValue = null;

    /**
     * @param  ?HrisUpdateEmployeeRequestDtoHomeLocationStateValue  $value
     * @param  string|float|bool|HrisUpdateEmployeeRequestDtoSourceValueHomeLocationState4|array<mixed>|null  $sourceValue
     */
    public function __construct(?HrisUpdateEmployeeRequestDtoHomeLocationStateValue $value = null, string|float|bool|HrisUpdateEmployeeRequestDtoSourceValueHomeLocationState4|array|null $sourceValue = null)
    {
        $this->value = $value;
        $this->sourceValue = $sourceValue;
    }
}