<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** The type of the national identity number */
enum HrisCreateEmployeeRequestDtoNationalIdentityNumberValue: string
{
    case Ssn = 'ssn';
    case Nin = 'nin';
    case Sin = 'sin';
    case Nid = 'nid';
    case Pin = 'pin';
    case Umcn = 'umcn';
    case Pic = 'pic';
    case Ric = 'ric';
    case Idnum = 'idnum';
    case Cid = 'cid';
    case Nidnr = 'nidnr';
    case Pan = 'pan';
    case Aadhaar = 'aadhaar';
    case Epic = 'epic';
    case Ptn = 'ptn';
    case Tin = 'tin';
    case Uprc = 'uprc';
    case Pcode = 'pcode';
    case Ssi = 'ssi';
    case Cedula = 'cedula';
    case Passport = 'passport';
    case Voterid = 'voterid';
    case Ntin = 'ntin';
    case Bn = 'bn';
    case Fnr = 'fnr';
    case Mva = 'mva';
    case CivilId = 'civil_id';
    case Cnic = 'cnic';
    case Nric = 'nric';
    case Fin = 'fin';
    case Uen = 'uen';
    case Registrationnumber = 'registrationnumber';
    case Nic = 'nic';
    case Personnummer = 'personnummer';
    case Ahv = 'ahv';
    case Id = 'id';
    case Eid = 'eid';
    case Va = 'va';
    case Pid = 'pid';
    case Nrt = 'nrt';
    case Nipt = 'nipt';
    case Cbu = 'cbu';
    case Cuit = 'cuit';
    case Dni = 'dni';
    case Businessid = 'businessid';
    case Vnr = 'vnr';
    case Abn = 'abn';
    case Acn = 'acn';
    case Tfn = 'tfn';
    case Jmbg = 'jmbg';
    case Bis = 'bis';
    case Insz = 'insz';
    case Nn = 'nn';
    case Egn = 'egn';
    case Pnf = 'pnf';
    case Vat = 'vat';
    case Cnpj = 'cnpj';
    case Unp = 'unp';
    case Gst = 'gst';
    case Pst = 'pst';
    case Qst = 'qst';
    case Ni = 'ni';
    case Dic = 'dic';
    case Rc = 'rc';
    case Uid = 'uid';
    case Rut = 'rut';
    case Uscc = 'uscc';
    case Cpf = 'cpf';
    case Cpj = 'cpj';
    case Cr = 'cr';
    case Stnr = 'stnr';
    case Svnr = 'svnr';
    case Ncf = 'ncf';
    case Rnc = 'rnc';
    case Nif = 'nif';
    case Ci = 'ci';
    case Ik = 'ik';
    case Kmkr = 'kmkr';
    case Registrikood = 'registrikood';
    case Tn = 'tn';
    case Ruc = 'ruc';
    case Nit = 'nit';
    case Alv = 'alv';
    case Hetu = 'hetu';
    case Ytunnus = 'ytunnus';
    case Vn = 'vn';
    case Utr = 'utr';
    case Nifp = 'nifp';
    case Amka = 'amka';
    case Cui = 'cui';
    case Nir = 'nir';
    case Siren = 'siren';
    case Siret = 'siret';
    case Tva = 'tva';
    case Oib = 'oib';
    case Hkid = 'hkid';
    case Anum = 'anum';
    case Kennitala = 'kennitala';
    case Vsk = 'vsk';
    case Npwp = 'npwp';
    case Pps = 'pps';
    case Gstin = 'gstin';
    case Idnr = 'idnr';
    case Hr = 'hr';
    case Aic = 'aic';
    case Codicefiscale = 'codicefiscale';
    case Iva = 'iva';
    case Peid = 'peid';
    case Asmens = 'asmens';
    case Pvm = 'pvm';
    case Other = 'other';
    case Unknown = 'unknown';
}
