<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** HrisUpdateEmploymentRequestDtoDurationUnit - The duration unit of the work time */
class HrisUpdateEmploymentRequestDtoDurationUnit
{
    /**
     * The unified value for the period.
     *
     * @var ?HrisUpdateEmploymentRequestDtoWorkTimeValue $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\HrisUpdateEmploymentRequestDtoWorkTimeValue|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?HrisUpdateEmploymentRequestDtoWorkTimeValue $value = null;

    /**
     *
     * @var string|float|bool|HrisUpdateEmploymentRequestDtoSourceValueWorkTime4|array<mixed>|null $sourceValue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_value')]
    #[\Speakeasy\Serializer\Annotation\Type('string|float|bool|\StackOne\client\Models\Components\HrisUpdateEmploymentRequestDtoSourceValueWorkTime4|array<mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public string|float|bool|HrisUpdateEmploymentRequestDtoSourceValueWorkTime4|array|null $sourceValue = null;

    /**
     * @param  ?HrisUpdateEmploymentRequestDtoWorkTimeValue  $value
     * @param  string|float|bool|HrisUpdateEmploymentRequestDtoSourceValueWorkTime4|array<mixed>|null  $sourceValue
     * @phpstan-pure
     */
    public function __construct(?HrisUpdateEmploymentRequestDtoWorkTimeValue $value = null, string|float|bool|HrisUpdateEmploymentRequestDtoSourceValueWorkTime4|array|null $sourceValue = null)
    {
        $this->value = $value;
        $this->sourceValue = $sourceValue;
    }
}