<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** HrisDocumentApiModelCategory - The category of the the document */
class HrisDocumentApiModelCategory
{
    /**
     * The category of the file
     *
     * @var ?HrisDocumentApiModelValue $value
     */
    #[\JMS\Serializer\Annotation\SerializedName('value')]
    #[\JMS\Serializer\Annotation\Type('\StackOne\client\Models\Components\HrisDocumentApiModelValue|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?HrisDocumentApiModelValue $value = null;

    /**
     *
     * @var string|float|bool|HrisDocumentApiModelSourceValue4|array<mixed>|null $sourceValue
     */
    #[\JMS\Serializer\Annotation\SerializedName('source_value')]
    #[\JMS\Serializer\Annotation\Type('string|float|bool|\StackOne\client\Models\Components\HrisDocumentApiModelSourceValue4|array<mixed>')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public string|float|bool|HrisDocumentApiModelSourceValue4|array|null $sourceValue = null;

    /**
     * @param  ?HrisDocumentApiModelValue  $value
     * @param  string|float|bool|HrisDocumentApiModelSourceValue4|array<mixed>|null  $sourceValue
     */
    public function __construct(?HrisDocumentApiModelValue $value = null, string|float|bool|HrisDocumentApiModelSourceValue4|array|null $sourceValue = null)
    {
        $this->value = $value;
        $this->sourceValue = $sourceValue;
    }
}