<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/**
 * HrisUpdateEmploymentRequestDtoEmploymentType - The type of employment (e.g., contractor, permanent)
 *
 * @deprecated  class: This will be removed in a future release, please migrate away from it as soon as possible.
 */
class HrisUpdateEmploymentRequestDtoEmploymentType
{
    /**
     * The type of the employment.
     *
     * @var ?HrisUpdateEmploymentRequestDtoEmploymentTypeValue $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\HrisUpdateEmploymentRequestDtoEmploymentTypeValue|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?HrisUpdateEmploymentRequestDtoEmploymentTypeValue $value = null;

    /**
     * The source value of the employment type.
     *
     * @var string|float|bool|HrisUpdateEmploymentRequestDtoSourceValueEmploymentType4|array<mixed>|null $sourceValue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_value')]
    #[\Speakeasy\Serializer\Annotation\Type('string|float|bool|\StackOne\client\Models\Components\HrisUpdateEmploymentRequestDtoSourceValueEmploymentType4|array<mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public string|float|bool|HrisUpdateEmploymentRequestDtoSourceValueEmploymentType4|array|null $sourceValue = null;

    /**
     * @param  ?HrisUpdateEmploymentRequestDtoEmploymentTypeValue  $value
     * @param  string|float|bool|HrisUpdateEmploymentRequestDtoSourceValueEmploymentType4|array<mixed>|null  $sourceValue
     * @phpstan-pure
     */
    public function __construct(?HrisUpdateEmploymentRequestDtoEmploymentTypeValue $value = null, string|float|bool|HrisUpdateEmploymentRequestDtoSourceValueEmploymentType4|array|null $sourceValue = null)
    {
        $this->value = $value;
        $this->sourceValue = $sourceValue;
    }
}