<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** HrisUpdateEmployeeRequestDtoEmployment - The employee employment */
class HrisUpdateEmployeeRequestDtoEmployment
{
    /**
     * Custom Unified Fields configured in your StackOne project
     *
     * @var ?array<string, mixed> $unifiedCustomFields
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('unified_custom_fields')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $unifiedCustomFields = null;

    /**
     * The job title of the employee
     *
     * @var ?string $jobTitle
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('job_title')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $jobTitle = null;

    /**
     * The pay rate for the employee
     *
     * @var ?string $payRate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pay_rate')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $payRate = null;

    /**
     * The pay period
     *
     * @var ?HrisUpdateEmployeeRequestDtoPayPeriod $payPeriod
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pay_period')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\HrisUpdateEmployeeRequestDtoPayPeriod|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?HrisUpdateEmployeeRequestDtoPayPeriod $payPeriod = null;

    /**
     * The pay frequency
     *
     * @var ?HrisUpdateEmployeeRequestDtoPayFrequency $payFrequency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pay_frequency')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\HrisUpdateEmployeeRequestDtoPayFrequency|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?HrisUpdateEmployeeRequestDtoPayFrequency $payFrequency = null;

    /**
     * The currency used for pay
     *
     * @var ?string $payCurrency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pay_currency')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $payCurrency = null;

    /**
     * The end date of employment
     *
     * @var ?\DateTime $endDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('end_date')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $endDate = null;

    /**
     * Represents the employee’s position within the organizational hierarchy.
     *
     * @var ?HrisUpdateEmployeeRequestDtoGrade $grade
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('grade')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\HrisUpdateEmployeeRequestDtoGrade|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?HrisUpdateEmployeeRequestDtoGrade $grade = null;

    /**
     * The type of employment (e.g., contractor, permanent)
     *
     * @var ?HrisUpdateEmployeeRequestDtoEmploymentEmploymentType $employmentType
     * @deprecated  field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('employment_type')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\HrisUpdateEmployeeRequestDtoEmploymentEmploymentType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?HrisUpdateEmployeeRequestDtoEmploymentEmploymentType $employmentType = null;

    /**
     * The employment work schedule type (e.g., full-time, part-time)
     *
     * @var ?HrisUpdateEmployeeRequestDtoEmploymentEmploymentContractType $employmentContractType
     * @deprecated  field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('employment_contract_type')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\HrisUpdateEmployeeRequestDtoEmploymentEmploymentContractType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?HrisUpdateEmployeeRequestDtoEmploymentEmploymentContractType $employmentContractType = null;

    /**
     * The type of employment
     *
     * @var ?HrisUpdateEmployeeRequestDtoType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\HrisUpdateEmployeeRequestDtoType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?HrisUpdateEmployeeRequestDtoType $type = null;

    /**
     * The employment work schedule type
     *
     * @var ?HrisUpdateEmployeeRequestDtoContractType $contractType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('contract_type')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\HrisUpdateEmployeeRequestDtoContractType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?HrisUpdateEmployeeRequestDtoContractType $contractType = null;

    /**
     *
     * @var ?HrisUpdateEmployeeRequestDtoWorkTime $workTime
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('work_time')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\HrisUpdateEmployeeRequestDtoWorkTime|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?HrisUpdateEmployeeRequestDtoWorkTime $workTime = null;

    /**
     * The payroll code of the employee
     *
     * @var ?string $payrollCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('payroll_code')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $payrollCode = null;

    /**
     * Value to pass through to the provider
     *
     * @var ?array<string, mixed> $passthrough
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('passthrough')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $passthrough = null;

    /**
     * The employee effective date
     *
     * @var ?\DateTime $effectiveDate
     * @deprecated  field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('effective_date')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $effectiveDate = null;

    /**
     * @param  ?array<string, mixed>  $unifiedCustomFields
     * @param  ?string  $jobTitle
     * @param  ?string  $payRate
     * @param  ?HrisUpdateEmployeeRequestDtoPayPeriod  $payPeriod
     * @param  ?HrisUpdateEmployeeRequestDtoPayFrequency  $payFrequency
     * @param  ?string  $payCurrency
     * @param  ?\DateTime  $endDate
     * @param  ?HrisUpdateEmployeeRequestDtoGrade  $grade
     * @param  ?HrisUpdateEmployeeRequestDtoEmploymentEmploymentType  $employmentType
     * @param  ?HrisUpdateEmployeeRequestDtoEmploymentEmploymentContractType  $employmentContractType
     * @param  ?HrisUpdateEmployeeRequestDtoType  $type
     * @param  ?HrisUpdateEmployeeRequestDtoContractType  $contractType
     * @param  ?HrisUpdateEmployeeRequestDtoWorkTime  $workTime
     * @param  ?string  $payrollCode
     * @param  ?array<string, mixed>  $passthrough
     * @param  ?\DateTime  $effectiveDate
     * @phpstan-pure
     */
    public function __construct(?array $unifiedCustomFields = null, ?string $jobTitle = null, ?string $payRate = null, ?HrisUpdateEmployeeRequestDtoPayPeriod $payPeriod = null, ?HrisUpdateEmployeeRequestDtoPayFrequency $payFrequency = null, ?string $payCurrency = null, ?\DateTime $endDate = null, ?HrisUpdateEmployeeRequestDtoGrade $grade = null, ?HrisUpdateEmployeeRequestDtoEmploymentEmploymentType $employmentType = null, ?HrisUpdateEmployeeRequestDtoEmploymentEmploymentContractType $employmentContractType = null, ?HrisUpdateEmployeeRequestDtoType $type = null, ?HrisUpdateEmployeeRequestDtoContractType $contractType = null, ?HrisUpdateEmployeeRequestDtoWorkTime $workTime = null, ?string $payrollCode = null, ?array $passthrough = null, ?\DateTime $effectiveDate = null)
    {
        $this->unifiedCustomFields = $unifiedCustomFields;
        $this->jobTitle = $jobTitle;
        $this->payRate = $payRate;
        $this->payPeriod = $payPeriod;
        $this->payFrequency = $payFrequency;
        $this->payCurrency = $payCurrency;
        $this->endDate = $endDate;
        $this->grade = $grade;
        $this->employmentType = $employmentType;
        $this->employmentContractType = $employmentContractType;
        $this->type = $type;
        $this->contractType = $contractType;
        $this->workTime = $workTime;
        $this->payrollCode = $payrollCode;
        $this->passthrough = $passthrough;
        $this->effectiveDate = $effectiveDate;
    }
}