<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class HrisUpdateEmployeeRequestDtoSourceValueEmploymentEmploymentContractType4
{

    public function __construct()
    {
    }
}