<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class HrisUpdateEmployeeRequestDtoWorkTime
{
    /**
     * The work time duration in ISO 8601 duration format
     *
     * @var ?string $duration
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('duration')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $duration = null;

    /**
     * The duration unit of the work time
     *
     * @var ?HrisUpdateEmployeeRequestDtoDurationUnit $durationUnit
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('duration_unit')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\HrisUpdateEmployeeRequestDtoDurationUnit|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?HrisUpdateEmployeeRequestDtoDurationUnit $durationUnit = null;

    /**
     * @param  ?string  $duration
     * @param  ?HrisUpdateEmployeeRequestDtoDurationUnit  $durationUnit
     * @phpstan-pure
     */
    public function __construct(?string $duration = null, ?HrisUpdateEmployeeRequestDtoDurationUnit $durationUnit = null)
    {
        $this->duration = $duration;
        $this->durationUnit = $durationUnit;
    }
}