<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** HRISGroupType - The type of the group */
class HRISGroupType
{
    /**
     *
     * @var ?HRISGroupValue $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\HRISGroupValue|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?HRISGroupValue $value = null;

    /**
     *
     * @var string|float|bool|HRISGroupSourceValue4|array<mixed>|null $sourceValue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_value')]
    #[\Speakeasy\Serializer\Annotation\Type('string|float|bool|\StackOne\client\Models\Components\HRISGroupSourceValue4|array<mixed>')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public string|float|bool|HRISGroupSourceValue4|array|null $sourceValue = null;

    /**
     * @param  ?HRISGroupValue  $value
     * @param  string|float|bool|HRISGroupSourceValue4|array<mixed>|null  $sourceValue
     */
    public function __construct(?HRISGroupValue $value = null, string|float|bool|HRISGroupSourceValue4|array|null $sourceValue = null)
    {
        $this->value = $value;
        $this->sourceValue = $sourceValue;
    }
}