<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** HrisCreateEmployeeRequestDtoPeriod - The period of the work time */
class HrisCreateEmployeeRequestDtoPeriod
{
    /**
     * The unified value for the period.
     *
     * @var ?HrisCreateEmployeeRequestDtoEmploymentWorkTimeValue $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\HrisCreateEmployeeRequestDtoEmploymentWorkTimeValue|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?HrisCreateEmployeeRequestDtoEmploymentWorkTimeValue $value = null;

    /**
     *
     * @var string|float|bool|HrisCreateEmployeeRequestDtoSourceValueEmploymentWorkTime4|array<mixed>|null $sourceValue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_value')]
    #[\Speakeasy\Serializer\Annotation\Type('string|float|bool|\StackOne\client\Models\Components\HrisCreateEmployeeRequestDtoSourceValueEmploymentWorkTime4|array<mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public string|float|bool|HrisCreateEmployeeRequestDtoSourceValueEmploymentWorkTime4|array|null $sourceValue = null;

    /**
     * @param  ?HrisCreateEmployeeRequestDtoEmploymentWorkTimeValue  $value
     * @param  string|float|bool|HrisCreateEmployeeRequestDtoSourceValueEmploymentWorkTime4|array<mixed>|null  $sourceValue
     * @phpstan-pure
     */
    public function __construct(?HrisCreateEmployeeRequestDtoEmploymentWorkTimeValue $value = null, string|float|bool|HrisCreateEmployeeRequestDtoSourceValueEmploymentWorkTime4|array|null $sourceValue = null)
    {
        $this->value = $value;
        $this->sourceValue = $sourceValue;
    }
}