<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** HrisUpdateEmployeeRequestDtoCountry - The country code */
class HrisUpdateEmployeeRequestDtoCountry
{
    /**
     * The ISO3166-1 Alpha2 Code of the Country
     *
     * @var ?HrisUpdateEmployeeRequestDtoNationalIdentityNumberCountryValue $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\HrisUpdateEmployeeRequestDtoNationalIdentityNumberCountryValue|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?HrisUpdateEmployeeRequestDtoNationalIdentityNumberCountryValue $value = null;

    /**
     *
     * @var string|float|bool|HrisUpdateEmployeeRequestDtoSourceValueNationalIdentityNumberCountry4|array<mixed>|null $sourceValue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_value')]
    #[\Speakeasy\Serializer\Annotation\Type('string|float|bool|\StackOne\client\Models\Components\HrisUpdateEmployeeRequestDtoSourceValueNationalIdentityNumberCountry4|array<mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public string|float|bool|HrisUpdateEmployeeRequestDtoSourceValueNationalIdentityNumberCountry4|array|null $sourceValue = null;

    /**
     * @param  ?HrisUpdateEmployeeRequestDtoNationalIdentityNumberCountryValue  $value
     * @param  string|float|bool|HrisUpdateEmployeeRequestDtoSourceValueNationalIdentityNumberCountry4|array<mixed>|null  $sourceValue
     * @phpstan-pure
     */
    public function __construct(?HrisUpdateEmployeeRequestDtoNationalIdentityNumberCountryValue $value = null, string|float|bool|HrisUpdateEmployeeRequestDtoSourceValueNationalIdentityNumberCountry4|array|null $sourceValue = null)
    {
        $this->value = $value;
        $this->sourceValue = $sourceValue;
    }
}