<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** The type of the benefit */
enum HRISBenefitValue: string
{
    case RetirementSavings = 'retirement_savings';
    case HealthSavings = 'health_savings';
    case Other = 'other';
    case HealthInsurance = 'health_insurance';
    case Insurance = 'insurance';
}
