<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** HrisCreateEmployeeRequestDtoPayPeriod - The pay period */
class HrisCreateEmployeeRequestDtoPayPeriod
{
    /**
     * The pay period of the job postings.
     *
     * @var ?HrisCreateEmployeeRequestDtoEmploymentValue $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\HrisCreateEmployeeRequestDtoEmploymentValue|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?HrisCreateEmployeeRequestDtoEmploymentValue $value = null;

    /**
     * The source value of the pay period.
     *
     * @var string|float|bool|HrisCreateEmployeeRequestDtoSourceValueEmployment4|array<mixed>|null $sourceValue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_value')]
    #[\Speakeasy\Serializer\Annotation\Type('string|float|bool|\StackOne\client\Models\Components\HrisCreateEmployeeRequestDtoSourceValueEmployment4|array<mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public string|float|bool|HrisCreateEmployeeRequestDtoSourceValueEmployment4|array|null $sourceValue = null;

    /**
     * @param  ?HrisCreateEmployeeRequestDtoEmploymentValue  $value
     * @param  string|float|bool|HrisCreateEmployeeRequestDtoSourceValueEmployment4|array<mixed>|null  $sourceValue
     * @phpstan-pure
     */
    public function __construct(?HrisCreateEmployeeRequestDtoEmploymentValue $value = null, string|float|bool|HrisCreateEmployeeRequestDtoSourceValueEmployment4|array|null $sourceValue = null)
    {
        $this->value = $value;
        $this->sourceValue = $sourceValue;
    }
}