<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** HrisUpdateEmployeeRequestDtoEmploymentStatus - The employee employment status */
class HrisUpdateEmployeeRequestDtoEmploymentStatus
{
    /**
     *
     * @var ?HrisUpdateEmployeeRequestDtoEmploymentStatusValue $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\HrisUpdateEmployeeRequestDtoEmploymentStatusValue|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?HrisUpdateEmployeeRequestDtoEmploymentStatusValue $value = null;

    /**
     *
     * @var string|float|bool|HrisUpdateEmployeeRequestDtoSourceValueEmploymentStatus4|array<mixed>|null $sourceValue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_value')]
    #[\Speakeasy\Serializer\Annotation\Type('string|float|bool|\StackOne\client\Models\Components\HrisUpdateEmployeeRequestDtoSourceValueEmploymentStatus4|array<mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public string|float|bool|HrisUpdateEmployeeRequestDtoSourceValueEmploymentStatus4|array|null $sourceValue = null;

    /**
     * @param  ?HrisUpdateEmployeeRequestDtoEmploymentStatusValue  $value
     * @param  string|float|bool|HrisUpdateEmployeeRequestDtoSourceValueEmploymentStatus4|array<mixed>|null  $sourceValue
     * @phpstan-pure
     */
    public function __construct(?HrisUpdateEmployeeRequestDtoEmploymentStatusValue $value = null, string|float|bool|HrisUpdateEmployeeRequestDtoSourceValueEmploymentStatus4|array|null $sourceValue = null)
    {
        $this->value = $value;
        $this->sourceValue = $sourceValue;
    }
}