<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** Images - Image assets for this provider */
class Images
{
    /**
     * URL of the square logo designed and used by StackOne for this provider
     *
     * @var ?string $logoUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('logo_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $logoUrl = null;

    /**
     * URL of the original provider logo (with logo and/or name aligned horizontally)
     *
     * @var ?string $originalLogoHorizontalUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('original_logo_horizontal_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $originalLogoHorizontalUrl = null;

    /**
     * @param  ?string  $logoUrl
     * @param  ?string  $originalLogoHorizontalUrl
     * @phpstan-pure
     */
    public function __construct(?string $logoUrl = null, ?string $originalLogoHorizontalUrl = null)
    {
        $this->logoUrl = $logoUrl;
        $this->originalLogoHorizontalUrl = $originalLogoHorizontalUrl;
    }
}