<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class Interview
{
    /**
     * Unique identifier
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * Provider's unique identifier
     *
     * @var ?string $remoteId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('remote_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $remoteId = null;

    /**
     * Custom Unified Fields configured in your StackOne project
     *
     * @var ?array<string, mixed> $unifiedCustomFields
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('unified_custom_fields')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $unifiedCustomFields = null;

    /**
     *
     * @var ?string $applicationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('application_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $applicationId = null;

    /**
     * Provider's unique identifier of the application
     *
     * @var ?string $remoteApplicationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('remote_application_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $remoteApplicationId = null;

    /**
     *
     * @var ?string $interviewStageId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('interview_stage_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $interviewStageId = null;

    /**
     * Provider's unique identifier of the interview stage
     *
     * @var ?string $remoteInterviewStageId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('remote_interview_stage_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $remoteInterviewStageId = null;

    /**
     *
     * @var ?InterviewInterviewStage $interviewStage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('interview_stage')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\InterviewInterviewStage|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?InterviewInterviewStage $interviewStage = null;

    /**
     *
     * @var ?InterviewInterviewStatus $interviewStatus
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('interview_status')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\InterviewInterviewStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?InterviewInterviewStatus $interviewStatus = null;

    /**
     * $interviewerIds
     *
     * @var ?array<string> $interviewerIds
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('interviewer_ids')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $interviewerIds = null;

    /**
     * Provider's unique identifiers of the interviewers
     *
     * @var ?array<string> $remoteInterviewerIds
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('remote_interviewer_ids')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $remoteInterviewerIds = null;

    /**
     * $interviewParts
     *
     * @var ?array<InterviewPart> $interviewParts
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('interview_parts')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\StackOne\client\Models\Components\InterviewPart>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $interviewParts = null;

    /**
     * $interviewers
     *
     * @var ?array<Interviewer> $interviewers
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('interviewers')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\StackOne\client\Models\Components\Interviewer>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $interviewers = null;

    /**
     * Interview start date
     *
     * @var ?\DateTime $startAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('start_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $startAt = null;

    /**
     * Interview end date
     *
     * @var ?\DateTime $endAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('end_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $endAt = null;

    /**
     *
     * @var ?string $meetingUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meeting_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $meetingUrl = null;

    /**
     * Interview created date
     *
     * @var ?\DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdAt = null;

    /**
     * Interview updated date
     *
     * @var ?\DateTime $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updated_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $updatedAt = null;

    /**
     * @param  ?string  $id
     * @param  ?string  $remoteId
     * @param  ?array<string, mixed>  $unifiedCustomFields
     * @param  ?string  $applicationId
     * @param  ?string  $remoteApplicationId
     * @param  ?string  $interviewStageId
     * @param  ?string  $remoteInterviewStageId
     * @param  ?InterviewInterviewStage  $interviewStage
     * @param  ?InterviewInterviewStatus  $interviewStatus
     * @param  ?array<string>  $interviewerIds
     * @param  ?array<string>  $remoteInterviewerIds
     * @param  ?array<InterviewPart>  $interviewParts
     * @param  ?array<Interviewer>  $interviewers
     * @param  ?\DateTime  $startAt
     * @param  ?\DateTime  $endAt
     * @param  ?string  $meetingUrl
     * @param  ?\DateTime  $createdAt
     * @param  ?\DateTime  $updatedAt
     */
    public function __construct(?string $id = null, ?string $remoteId = null, ?array $unifiedCustomFields = null, ?string $applicationId = null, ?string $remoteApplicationId = null, ?string $interviewStageId = null, ?string $remoteInterviewStageId = null, ?InterviewInterviewStage $interviewStage = null, ?InterviewInterviewStatus $interviewStatus = null, ?array $interviewerIds = null, ?array $remoteInterviewerIds = null, ?array $interviewParts = null, ?array $interviewers = null, ?\DateTime $startAt = null, ?\DateTime $endAt = null, ?string $meetingUrl = null, ?\DateTime $createdAt = null, ?\DateTime $updatedAt = null)
    {
        $this->id = $id;
        $this->remoteId = $remoteId;
        $this->unifiedCustomFields = $unifiedCustomFields;
        $this->applicationId = $applicationId;
        $this->remoteApplicationId = $remoteApplicationId;
        $this->interviewStageId = $interviewStageId;
        $this->remoteInterviewStageId = $remoteInterviewStageId;
        $this->interviewStage = $interviewStage;
        $this->interviewStatus = $interviewStatus;
        $this->interviewerIds = $interviewerIds;
        $this->remoteInterviewerIds = $remoteInterviewerIds;
        $this->interviewParts = $interviewParts;
        $this->interviewers = $interviewers;
        $this->startAt = $startAt;
        $this->endAt = $endAt;
        $this->meetingUrl = $meetingUrl;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
    }
}