<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class InterviewStatus
{
    /**
     * The status of the interview.
     *
     * @var ?ScheduledInterviewValue $value
     */
    #[\JMS\Serializer\Annotation\SerializedName('value')]
    #[\JMS\Serializer\Annotation\Type('\StackOne\client\Models\Components\ScheduledInterviewValue|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?ScheduledInterviewValue $value = null;

    /**
     * The source value of the interview status.
     *
     * @var string|float|bool|ScheduledInterviewSourceValue4|array<mixed>|null $sourceValue
     */
    #[\JMS\Serializer\Annotation\SerializedName('source_value')]
    #[\JMS\Serializer\Annotation\Type('string|float|bool|\StackOne\client\Models\Components\ScheduledInterviewSourceValue4|array<mixed>')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public string|float|bool|ScheduledInterviewSourceValue4|array|null $sourceValue = null;

    /**
     * @param  ?ScheduledInterviewValue  $value
     * @param  string|float|bool|ScheduledInterviewSourceValue4|array<mixed>|null  $sourceValue
     */
    public function __construct(?ScheduledInterviewValue $value = null, string|float|bool|ScheduledInterviewSourceValue4|array|null $sourceValue = null)
    {
        $this->value = $value;
        $this->sourceValue = $sourceValue;
    }
}