<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/**
 * JobDescription - The employee job description
 *
 * @deprecated  class: This will be removed in a future release, please migrate away from it as soon as possible.
 */
class JobDescription
{
    /**
     *
     * @var ?string $text
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('text')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $text = null;

    /**
     * @param  ?string  $text
     */
    public function __construct(?string $text = null)
    {
        $this->text = $text;
    }
}