<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** The type of the description. */
enum JobPostingContentSectionValue: string
{
    case Responsibilities = 'responsibilities';
    case Skills = 'skills';
    case Benefits = 'benefits';
    case CompanyOverview = 'company_overview';
    case Description = 'description';
    case Other = 'other';
    case UnmappedValue = 'unmapped_value';
}
