<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class JsonRpcMessageDto
{
    /**
     * JSON-RPC protocol version
     *
     * @var string $jsonrpc
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('jsonrpc')]
    public string $jsonrpc;

    /**
     * JSON-RPC method name
     *
     * @var string $method
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('method')]
    public string $method;

    /**
     * Method parameters (arbitrary JSON)
     *
     * @var ?Params $params
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('params')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\Params|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Params $params = null;

    /**
     * Request id (arbitrary JSON scalar)
     *
     * @var ?Id $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\Id|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Id $id = null;

    /**
     * @param  string  $jsonrpc
     * @param  string  $method
     * @param  ?Params  $params
     * @param  ?Id  $id
     * @phpstan-pure
     */
    public function __construct(string $jsonrpc, string $method, ?Params $params = null, ?Id $id = null)
    {
        $this->jsonrpc = $jsonrpc;
        $this->method = $method;
        $this->params = $params;
        $this->id = $id;
    }
}