<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class LanguageEnum
{
    /**
     * The unified locale code. For write operations: provide one of the listed enum values, or omit/set to "unmapped_value" to use source_value instead.
     *
     * @var ?LanguageEnumValue $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\LanguageEnumValue|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?LanguageEnumValue $value = null;

    /**
     * For read operations: the original language code from the provider. For write operations: fallback value used when value is omitted or "unmapped_value". You must ensure this matches the provider's format.
     *
     * @var string|float|bool|LanguageEnumSourceValue4|array<mixed>|null $sourceValue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_value')]
    #[\Speakeasy\Serializer\Annotation\Type('string|float|bool|\StackOne\client\Models\Components\LanguageEnumSourceValue4|array<mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public string|float|bool|LanguageEnumSourceValue4|array|null $sourceValue = null;

    /**
     * @param  ?LanguageEnumValue  $value
     * @param  string|float|bool|LanguageEnumSourceValue4|array<mixed>|null  $sourceValue
     * @phpstan-pure
     */
    public function __construct(?LanguageEnumValue $value = null, string|float|bool|LanguageEnumSourceValue4|array|null $sourceValue = null)
    {
        $this->value = $value;
        $this->sourceValue = $sourceValue;
    }
}