<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** LearningObjectType - The learning object type of the assignment */
class LearningObjectType
{
    /**
     * The StackOne unified learning object type.
     *
     * @var ?AssignmentLearningObjectTypeValue $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\AssignmentLearningObjectTypeValue|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AssignmentLearningObjectTypeValue $value = null;

    /**
     * The original learning object type from the provider before normalization.
     *
     * @var string|float|bool|AssignmentSourceValueLearningObjectType4|array<mixed>|null $sourceValue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_value')]
    #[\Speakeasy\Serializer\Annotation\Type('string|float|bool|\StackOne\client\Models\Components\AssignmentSourceValueLearningObjectType4|array<mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public string|float|bool|AssignmentSourceValueLearningObjectType4|array|null $sourceValue = null;

    /**
     * @param  ?AssignmentLearningObjectTypeValue  $value
     * @param  string|float|bool|AssignmentSourceValueLearningObjectType4|array<mixed>|null  $sourceValue
     * @phpstan-pure
     */
    public function __construct(?AssignmentLearningObjectTypeValue $value = null, string|float|bool|AssignmentSourceValueLearningObjectType4|array|null $sourceValue = null)
    {
        $this->value = $value;
        $this->sourceValue = $sourceValue;
    }
}