<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class LmsCreateAssignmentRequestDto
{
    /**
     * Value to pass through to the provider
     *
     * @var ?array<string, mixed> $passthrough
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('passthrough')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $passthrough = null;

    /**
     * The external reference associated with this assignment
     *
     * @var ?string $externalReference
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('external_reference')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $externalReference = null;

    /**
     * The learning_object_id associated with this assignment
     *
     * @var ?string $learningObjectId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('learning_object_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $learningObjectId = null;

    /**
     * The external reference of the learning object associated with this assignment
     *
     * @var ?string $learningObjectExternalReference
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('learning_object_external_reference')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $learningObjectExternalReference = null;

    /**
     * The progress associated with this assigment
     *
     * @var ?float $progress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('progress')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $progress = null;

    /**
     * The date the assignment was created
     *
     * @var ?string $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $createdAt = null;

    /**
     * The date the assignment is due to be completed
     *
     * @var ?string $dueDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('due_date')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $dueDate = null;

    /**
     * The status of the assignment
     *
     * @var ?LmsCreateAssignmentRequestDtoStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\LmsCreateAssignmentRequestDtoStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?LmsCreateAssignmentRequestDtoStatus $status = null;

    /**
     * @param  ?array<string, mixed>  $passthrough
     * @param  ?string  $externalReference
     * @param  ?string  $learningObjectId
     * @param  ?string  $learningObjectExternalReference
     * @param  ?float  $progress
     * @param  ?string  $createdAt
     * @param  ?string  $dueDate
     * @param  ?LmsCreateAssignmentRequestDtoStatus  $status
     */
    public function __construct(?array $passthrough = null, ?string $externalReference = null, ?string $learningObjectId = null, ?string $learningObjectExternalReference = null, ?float $progress = null, ?string $createdAt = null, ?string $dueDate = null, ?LmsCreateAssignmentRequestDtoStatus $status = null)
    {
        $this->passthrough = $passthrough;
        $this->externalReference = $externalReference;
        $this->learningObjectId = $learningObjectId;
        $this->learningObjectExternalReference = $learningObjectExternalReference;
        $this->progress = $progress;
        $this->createdAt = $createdAt;
        $this->dueDate = $dueDate;
        $this->status = $status;
    }
}