<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** LmsCreateContentRequestDtoContentLaunchMethod - The content launch method associated with this content */
class LmsCreateContentRequestDtoContentLaunchMethod
{
    /**
     *
     * @var ?LmsCreateContentRequestDtoContentLaunchMethodValue $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\LmsCreateContentRequestDtoContentLaunchMethodValue|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?LmsCreateContentRequestDtoContentLaunchMethodValue $value = null;

    /**
     *
     * @var string|float|bool|LmsCreateContentRequestDtoSourceValueContentLaunchMethod4|array<mixed>|null $sourceValue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_value')]
    #[\Speakeasy\Serializer\Annotation\Type('string|float|bool|\StackOne\client\Models\Components\LmsCreateContentRequestDtoSourceValueContentLaunchMethod4|array<mixed>')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public string|float|bool|LmsCreateContentRequestDtoSourceValueContentLaunchMethod4|array|null $sourceValue = null;

    /**
     * @param  ?LmsCreateContentRequestDtoContentLaunchMethodValue  $value
     * @param  string|float|bool|LmsCreateContentRequestDtoSourceValueContentLaunchMethod4|array<mixed>|null  $sourceValue
     */
    public function __construct(?LmsCreateContentRequestDtoContentLaunchMethodValue $value = null, string|float|bool|LmsCreateContentRequestDtoSourceValueContentLaunchMethod4|array|null $sourceValue = null)
    {
        $this->value = $value;
        $this->sourceValue = $sourceValue;
    }
}