<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class LmsCreateCompletionRequestDto
{
    /**
     * The external reference of the learning object associated with this completion, this is the main identifier for creating completions.
     *
     * @var string $learningObjectExternalReference
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('learning_object_external_reference')]
    public string $learningObjectExternalReference;

    /**
     * Value to pass through to the provider
     *
     * @var ?array<string, mixed> $passthrough
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('passthrough')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $passthrough = null;

    /**
     * The result of the completion
     *
     * @var ?LmsCreateCompletionRequestDtoResult $result
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('result')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\LmsCreateCompletionRequestDtoResult|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?LmsCreateCompletionRequestDtoResult $result = null;

    /**
     * The date the content was completed
     *
     * @var ?\DateTime $completedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('completed_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $completedAt = null;

    /**
     * The id of the learning object associated with this completion. This is not required unless specified in an integration.
     *
     * @var ?string $learningObjectId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('learning_object_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $learningObjectId = null;

    /**
     * ISO 8601 duration format representing the time spent on completing the learning object
     *
     * @var ?string $timeSpent
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('time_spent')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $timeSpent = null;

    /**
     * The external reference associated with this content
     *
     * @var ?string $contentExternalReference
     * @deprecated  field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('content_external_reference')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $contentExternalReference = null;

    /**
     * The content ID associated with this completion
     *
     * @var ?string $contentId
     * @deprecated  field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('content_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $contentId = null;

    /**
     * @param  string  $learningObjectExternalReference
     * @param  ?array<string, mixed>  $passthrough
     * @param  ?LmsCreateCompletionRequestDtoResult  $result
     * @param  ?\DateTime  $completedAt
     * @param  ?string  $learningObjectId
     * @param  ?string  $timeSpent
     * @param  ?string  $contentExternalReference
     * @param  ?string  $contentId
     * @phpstan-pure
     */
    public function __construct(string $learningObjectExternalReference, ?array $passthrough = null, ?LmsCreateCompletionRequestDtoResult $result = null, ?\DateTime $completedAt = null, ?string $learningObjectId = null, ?string $timeSpent = null, ?string $contentExternalReference = null, ?string $contentId = null)
    {
        $this->learningObjectExternalReference = $learningObjectExternalReference;
        $this->passthrough = $passthrough;
        $this->result = $result;
        $this->completedAt = $completedAt;
        $this->learningObjectId = $learningObjectId;
        $this->timeSpent = $timeSpent;
        $this->contentExternalReference = $contentExternalReference;
        $this->contentId = $contentId;
    }
}