<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


enum LmsUpsertContentRequestDtoValue: string
{
    case Video = 'video';
    case Quiz = 'quiz';
    case Document = 'document';
    case Audio = 'audio';
    case Article = 'article';
    case Book = 'book';
    case Event = 'event';
    case Course = 'course';
    case Collection = 'collection';
    case Interactive = 'interactive';
    case UnmappedValue = 'unmapped_value';
}
