<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class MessagingMessageResultData
{
    /**
     * Unique identifier
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * Provider's unique identifier
     *
     * @var ?string $remoteId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('remote_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $remoteId = null;

    /**
     * Content of the message
     *
     * @var ?MessagingMessageResultContent $content
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('content')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\MessagingMessageResultContent|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?MessagingMessageResultContent $content = null;

    /**
     * ID of the parent message if this is a reply
     *
     * @var ?string $parentMessageId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('parent_message_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $parentMessageId = null;

    /**
     * List of attachments in the message
     *
     * @var ?array<string> $attachments
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('attachments')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $attachments = null;

    /**
     * Author of the message
     *
     * @var ?MessagingMessageResultAuthor $author
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('author')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\MessagingMessageResultAuthor|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?MessagingMessageResultAuthor $author = null;

    /**
     * Timestamp when the message was created
     *
     * @var ?\DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdAt = null;

    /**
     * Timestamp when the message was last updated
     *
     * @var ?\DateTime $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updated_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $updatedAt = null;

    /**
     * @param  ?string  $id
     * @param  ?string  $remoteId
     * @param  ?MessagingMessageResultContent  $content
     * @param  ?string  $parentMessageId
     * @param  ?array<string>  $attachments
     * @param  ?MessagingMessageResultAuthor  $author
     * @param  ?\DateTime  $createdAt
     * @param  ?\DateTime  $updatedAt
     * @phpstan-pure
     */
    public function __construct(?string $id = null, ?string $remoteId = null, ?MessagingMessageResultContent $content = null, ?string $parentMessageId = null, ?array $attachments = null, ?MessagingMessageResultAuthor $author = null, ?\DateTime $createdAt = null, ?\DateTime $updatedAt = null)
    {
        $this->id = $id;
        $this->remoteId = $remoteId;
        $this->content = $content;
        $this->parentMessageId = $parentMessageId;
        $this->attachments = $attachments;
        $this->author = $author;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
    }
}