<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class MessagingConversation
{
    /**
     * Unique identifier
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * Provider's unique identifier
     *
     * @var ?string $remoteId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('remote_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $remoteId = null;

    /**
     * List of participant user IDs in the conversation
     *
     * @var ?array<string> $participants
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('participants')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $participants = null;

    /**
     * Name or title of the conversation
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * Whether the conversation is private
     *
     * @var bool|Private2|null $private
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('private')]
    #[\Speakeasy\Serializer\Annotation\Type('bool|\StackOne\client\Models\Components\Private2|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public bool|Private2|null $private = null;

    /**
     * Timestamp when the conversation was created
     *
     * @var ?\DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdAt = null;

    /**
     * Timestamp of the last message in the conversation
     *
     * @var ?\DateTime $lastMessageAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('last_message_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $lastMessageAt = null;

    /**
     * @param  ?string  $id
     * @param  ?string  $remoteId
     * @param  ?array<string>  $participants
     * @param  ?string  $name
     * @param  bool|Private2|null  $private
     * @param  ?\DateTime  $createdAt
     * @param  ?\DateTime  $lastMessageAt
     * @phpstan-pure
     */
    public function __construct(?string $id = null, ?string $remoteId = null, ?array $participants = null, ?string $name = null, bool|Private2|null $private = null, ?\DateTime $createdAt = null, ?\DateTime $lastMessageAt = null)
    {
        $this->id = $id;
        $this->remoteId = $remoteId;
        $this->participants = $participants;
        $this->name = $name;
        $this->private = $private;
        $this->createdAt = $createdAt;
        $this->lastMessageAt = $lastMessageAt;
    }
}