<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class NationalIdentityNumberApiModel
{
    /**
     *
     * @var ?string $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $value = null;

    /**
     *
     * @var ?NationalIdentityNumberApiModelType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\NationalIdentityNumberApiModelType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?NationalIdentityNumberApiModelType $type = null;

    /**
     * The country code
     *
     * @var ?Country $country
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('country')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\Country|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Country $country = null;

    /**
     * @param  ?string  $value
     * @param  ?NationalIdentityNumberApiModelType  $type
     * @param  ?Country  $country
     * @phpstan-pure
     */
    public function __construct(?string $value = null, ?NationalIdentityNumberApiModelType $type = null, ?Country $country = null)
    {
        $this->value = $value;
        $this->type = $type;
        $this->country = $country;
    }
}