<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** Organization - Organization associated with the ticket */
class Organization
{
    /**
     * Unique identifier
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * Provider's unique identifier
     *
     * @var ?string $remoteId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('remote_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $remoteId = null;

    /**
     * The domain of the organization
     *
     * @var ?string $domain
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('domain')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $domain = null;

    /**
     * The name of the organization
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * @param  ?string  $id
     * @param  ?string  $remoteId
     * @param  ?string  $domain
     * @param  ?string  $name
     * @phpstan-pure
     */
    public function __construct(?string $id = null, ?string $remoteId = null, ?string $domain = null, ?string $name = null)
    {
        $this->id = $id;
        $this->remoteId = $remoteId;
        $this->domain = $domain;
        $this->name = $name;
    }
}