<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class PhoneNumber
{
    /**
     * Type of phone number
     *
     * @var ?PhoneNumberType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\PhoneNumberType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PhoneNumberType $type = null;

    /**
     * Phone number string
     *
     * @var ?string $phone
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('phone')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $phone = null;

    /**
     * @param  ?PhoneNumberType  $type
     * @param  ?string  $phone
     * @phpstan-pure
     */
    public function __construct(?PhoneNumberType $type = null, ?string $phone = null)
    {
        $this->type = $type;
        $this->phone = $phone;
    }
}