<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class PushMessageContents
{
    /**
     *
     * @var ?string $body
     */
    #[\JMS\Serializer\Annotation\SerializedName('body')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $body = null;

    /**
     * @param  ?string  $body
     */
    public function __construct(?string $body = null)
    {
        $this->body = $body;
    }
}