<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class ShiftBreak
{
    /**
     * The unique identifier of the break
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * The start time of the break
     *
     * @var ?\DateTime $startTime
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('start_time')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $startTime = null;

    /**
     * The end time of the break
     *
     * @var ?\DateTime $endTime
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('end_time')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $endTime = null;

    /**
     * The duration of the break in ISO 8601 duration format
     *
     * @var ?string $duration
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('duration')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $duration = null;

    /**
     * Whether the break is paid
     *
     * @var bool|IsPaid2|null $isPaid
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('is_paid')]
    #[\Speakeasy\Serializer\Annotation\Type('bool|\StackOne\client\Models\Components\IsPaid2|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public bool|IsPaid2|null $isPaid = null;

    /**
     * The date and time the break was created
     *
     * @var ?\DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdAt = null;

    /**
     * The date and time the break was last updated
     *
     * @var ?\DateTime $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updated_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $updatedAt = null;

    /**
     * @param  ?string  $id
     * @param  ?\DateTime  $startTime
     * @param  ?\DateTime  $endTime
     * @param  ?string  $duration
     * @param  bool|IsPaid2|null  $isPaid
     * @param  ?\DateTime  $createdAt
     * @param  ?\DateTime  $updatedAt
     * @phpstan-pure
     */
    public function __construct(?string $id = null, ?\DateTime $startTime = null, ?\DateTime $endTime = null, ?string $duration = null, bool|IsPaid2|null $isPaid = null, ?\DateTime $createdAt = null, ?\DateTime $updatedAt = null)
    {
        $this->id = $id;
        $this->startTime = $startTime;
        $this->endTime = $endTime;
        $this->duration = $duration;
        $this->isPaid = $isPaid;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
    }
}