<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class TaskCommentApiModel
{
    /**
     * The Employee ID of the author of the comment
     *
     * @var ?string $authorEmployeeId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('author_employee_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $authorEmployeeId = null;

    /**
     * The text of the comment
     *
     * @var ?string $comment
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('comment')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $comment = null;

    /**
     * The creation date of this comment
     *
     * @var ?\DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdAt = null;

    /**
     * @param  ?string  $authorEmployeeId
     * @param  ?string  $comment
     * @param  ?\DateTime  $createdAt
     * @phpstan-pure
     */
    public function __construct(?string $authorEmployeeId = null, ?string $comment = null, ?\DateTime $createdAt = null)
    {
        $this->authorEmployeeId = $authorEmployeeId;
        $this->comment = $comment;
        $this->createdAt = $createdAt;
    }
}