<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class TicketingUserResultType
{
    /**
     * The type of the user.
     *
     * @var ?TicketingUserResultValue $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\TicketingUserResultValue|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TicketingUserResultValue $value = null;

    /**
     * The source value of the user type.
     *
     * @var string|float|bool|TicketingUserResultSourceValue4|array<mixed>|null $sourceValue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_value')]
    #[\Speakeasy\Serializer\Annotation\Type('string|float|bool|\StackOne\client\Models\Components\TicketingUserResultSourceValue4|array<mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public string|float|bool|TicketingUserResultSourceValue4|array|null $sourceValue = null;

    /**
     * @param  ?TicketingUserResultValue  $value
     * @param  string|float|bool|TicketingUserResultSourceValue4|array<mixed>|null  $sourceValue
     * @phpstan-pure
     */
    public function __construct(?TicketingUserResultValue $value = null, string|float|bool|TicketingUserResultSourceValue4|array|null $sourceValue = null)
    {
        $this->value = $value;
        $this->sourceValue = $sourceValue;
    }
}