<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** TicketingAttachmentResultFileFormat - The type of the file */
class TicketingAttachmentResultFileFormat
{
    /**
     * The file format of the file, expressed as a file extension
     *
     * @var ?TicketingAttachmentResultValue $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\TicketingAttachmentResultValue|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TicketingAttachmentResultValue $value = null;

    /**
     *
     * @var string|float|bool|TicketingAttachmentResultSourceValue4|array<mixed>|null $sourceValue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_value')]
    #[\Speakeasy\Serializer\Annotation\Type('string|float|bool|\StackOne\client\Models\Components\TicketingAttachmentResultSourceValue4|array<mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public string|float|bool|TicketingAttachmentResultSourceValue4|array|null $sourceValue = null;

    /**
     * @param  ?TicketingAttachmentResultValue  $value
     * @param  string|float|bool|TicketingAttachmentResultSourceValue4|array<mixed>|null  $sourceValue
     * @phpstan-pure
     */
    public function __construct(?TicketingAttachmentResultValue $value = null, string|float|bool|TicketingAttachmentResultSourceValue4|array|null $sourceValue = null)
    {
        $this->value = $value;
        $this->sourceValue = $sourceValue;
    }
}