<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class TicketingTicketStatus
{
    /**
     * The id of the ticket status.
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * The type of this status
     *
     * @var ?TicketingTicketStatusType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\TicketingTicketStatusType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TicketingTicketStatusType $type = null;

    /**
     * The name of the ticket status.
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * @param  ?string  $id
     * @param  ?TicketingTicketStatusType  $type
     * @param  ?string  $name
     * @phpstan-pure
     */
    public function __construct(?string $id = null, ?TicketingTicketStatusType $type = null, ?string $name = null)
    {
        $this->id = $id;
        $this->type = $type;
        $this->name = $name;
    }
}