<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


enum TimeEntriesValue: string
{
    case Approved = 'approved';
    case UnmappedValue = 'unmapped_value';
}
