<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** The connect session account type */
enum Type: string
{
    case Production = 'production';
    case Test = 'test';
}
