<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** UnifiedUploadRequestDtoCategory - The category object for associating uploaded files. If both an ID and a name are provided, the ID takes precedence. */
class UnifiedUploadRequestDtoCategory
{
    /**
     * The category name for associating uploaded files.
     *
     * @var ?string $value
     */
    #[\JMS\Serializer\Annotation\SerializedName('value')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $value = null;

    /**
     * The provider specific category for associating uploaded files, if provided, the value will be ignored.
     *
     * @var ?string $sourceValue
     */
    #[\JMS\Serializer\Annotation\SerializedName('source_value')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $sourceValue = null;

    /**
     * @param  ?string  $value
     * @param  ?string  $sourceValue
     */
    public function __construct(?string $value = null, ?string $sourceValue = null)
    {
        $this->value = $value;
        $this->sourceValue = $sourceValue;
    }
}