<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** UpdateEmployeeApiModelAvatar - The employee avatar */
class UpdateEmployeeApiModelAvatar
{
    /**
     *
     * @var ?string $url
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $url = null;

    /**
     *
     * @var ?string $base64
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('base64')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $base64 = null;

    /**
     * @param  ?string  $url
     * @param  ?string  $base64
     */
    public function __construct(?string $url = null, ?string $base64 = null)
    {
        $this->url = $url;
        $this->base64 = $base64;
    }
}