<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class WorkEligibility
{
    /**
     * Unique identifier
     *
     * @var ?string $id
     */
    #[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * Provider's unique identifier
     *
     * @var ?string $remoteId
     */
    #[\JMS\Serializer\Annotation\SerializedName('remote_id')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $remoteId = null;

    /**
     *
     * @var ?WorkEligibilityType $type
     */
    #[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('\StackOne\client\Models\Components\WorkEligibilityType|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?WorkEligibilityType $type = null;

    /**
     *
     * @var ?string $subType
     */
    #[\JMS\Serializer\Annotation\SerializedName('sub_type')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $subType = null;

    /**
     *
     * @var ?Document $document
     */
    #[\JMS\Serializer\Annotation\SerializedName('document')]
    #[\JMS\Serializer\Annotation\Type('\StackOne\client\Models\Components\Document|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?Document $document = null;

    /**
     *
     * @var ?\DateTime $validFrom
     */
    #[\JMS\Serializer\Annotation\SerializedName('valid_from')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $validFrom = null;

    /**
     *
     * @var ?\DateTime $validTo
     */
    #[\JMS\Serializer\Annotation\SerializedName('valid_to')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $validTo = null;

    /**
     * The country code of the issued by authority
     *
     * @var ?IssuedBy $issuedBy
     */
    #[\JMS\Serializer\Annotation\SerializedName('issued_by')]
    #[\JMS\Serializer\Annotation\Type('\StackOne\client\Models\Components\IssuedBy|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?IssuedBy $issuedBy = null;

    /**
     *
     * @var ?string $number
     */
    #[\JMS\Serializer\Annotation\SerializedName('number')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $number = null;

    /**
     * @param  ?string  $id
     * @param  ?string  $remoteId
     * @param  ?WorkEligibilityType  $type
     * @param  ?string  $subType
     * @param  ?Document  $document
     * @param  ?\DateTime  $validFrom
     * @param  ?\DateTime  $validTo
     * @param  ?IssuedBy  $issuedBy
     * @param  ?string  $number
     */
    public function __construct(?string $id = null, ?string $remoteId = null, ?WorkEligibilityType $type = null, ?string $subType = null, ?Document $document = null, ?\DateTime $validFrom = null, ?\DateTime $validTo = null, ?IssuedBy $issuedBy = null, ?string $number = null)
    {
        $this->id = $id;
        $this->remoteId = $remoteId;
        $this->type = $type;
        $this->subType = $subType;
        $this->document = $document;
        $this->validFrom = $validFrom;
        $this->validTo = $validTo;
        $this->issuedBy = $issuedBy;
        $this->number = $number;
    }
}