<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class WorkEligibilityType
{
    /**
     *
     * @var ?WorkEligibilityValue $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\WorkEligibilityValue|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?WorkEligibilityValue $value = null;

    /**
     *
     * @var string|float|bool|SourceType4|array<mixed>|null $sourceType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_type')]
    #[\Speakeasy\Serializer\Annotation\Type('string|float|bool|\StackOne\client\Models\Components\SourceType4|array<mixed>')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public string|float|bool|SourceType4|array|null $sourceType = null;

    /**
     * @param  ?WorkEligibilityValue  $value
     * @param  string|float|bool|SourceType4|array<mixed>|null  $sourceType
     */
    public function __construct(?WorkEligibilityValue $value = null, string|float|bool|SourceType4|array|null $sourceType = null)
    {
        $this->value = $value;
        $this->sourceType = $sourceType;
    }
}