<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** WorkEligibilityFileFormat - The file format of the file */
class WorkEligibilityFileFormat
{
    /**
     * The file format of the file, expressed as a file extension
     *
     * @var ?WorkEligibilityDocumentValue $value
     */
    #[\JMS\Serializer\Annotation\SerializedName('value')]
    #[\JMS\Serializer\Annotation\Type('\StackOne\client\Models\Components\WorkEligibilityDocumentValue|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?WorkEligibilityDocumentValue $value = null;

    /**
     *
     * @var string|float|bool|WorkEligibilitySourceValueDocument4|array<mixed>|null $sourceValue
     */
    #[\JMS\Serializer\Annotation\SerializedName('source_value')]
    #[\JMS\Serializer\Annotation\Type('string|float|bool|\StackOne\client\Models\Components\WorkEligibilitySourceValueDocument4|array<mixed>')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public string|float|bool|WorkEligibilitySourceValueDocument4|array|null $sourceValue = null;

    /**
     * @param  ?WorkEligibilityDocumentValue  $value
     * @param  string|float|bool|WorkEligibilitySourceValueDocument4|array<mixed>|null  $sourceValue
     */
    public function __construct(?WorkEligibilityDocumentValue $value = null, string|float|bool|WorkEligibilitySourceValueDocument4|array|null $sourceValue = null)
    {
        $this->value = $value;
        $this->sourceValue = $sourceValue;
    }
}